### ISSUE TITLE
Android Unity  GvrIntent.GetData() doesn't work.

### ISSUE THREAD

**Issue by ashinetyp** [googlevr/gvr-unity-sdk#597] opened 2017-05-28 14:21 UTC
Unity 5.61, it always returns null by  GvrIntent.GetData().
It seems intent is blocked by proxy activity. (Daydream paring UI)
The same symptom happens on 7.1 Daydream ready phone and 7.1 non Daydream ready phone.

**Comment by bopangzz** [comment] 2017-06-05 03:10
Thanks for the report. We will look into this issue.

**Comment by bopangzz** [comment] 2017-06-05 03:24
Also can you provide more information on how you setup the intent and when you call the GvrIntent.GetData()?

**Comment by gilgil28** [comment] 2017-06-22 14:30
I can confirm that the intent data is not passed. It might be because of the "get started" screen of the daydream in which you press and hold the home button.
Otherwise (if the device is already in the headset or cardboard) it works.

**Comment by gilgil28** [comment] 2017-08-29 15:18
Any progress? @bopangzz

**Comment by rusmaxham** [comment] 2017-11-03 22:39
This should be fixed now.

**Closed by rusmaxham** 2017-11-03 22:39 UTC
Labels: bug
