### ISSUE TITLE
GVR camera split rendering size error (largely rendered)

### ISSUE THREAD

**Issue by KyKimGlobepoint** [googlevr/gvr-unity-sdk#616] opened 2017-06-16 07:54 UTC
![temp](https://user-images.githubusercontent.com/29477265/27217308-4618b3e4-52b4-11e7-9bc8-8ad7db8c8aab.jpg)
Is there a feature that can modify the GVR screen size?
unity = 5.6.1p2
GVR SDK = 1.6

**Comment by vinhui** [comment] 2017-06-16 14:47
did you setup the right viewer with a qr code?

**Comment by KyKimGlobepoint** [comment] 2017-06-17 04:04
Yes....

**Comment by nahunhee** [comment] 2017-06-20 13:38
same error with compile error(OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_VALUE: Numeric argument out of range)

**Comment by KyKimGlobepoint** [comment] 2017-06-21 00:46
@nahunhee 
Is there a way to solve this issue?

**Comment by nahunhee** [comment] 2017-06-21 01:13
Yes!! Finally I found the solution!!!! 
In my case, the problem is ' Screen.Resolutions(1280, 800, true)'.
If you use Screen.Resolution, delete the code.

**Comment by KyKimGlobepoint** [comment] 2017-06-21 01:43
@nahunhee
wow!  my problem was the same.
I was in the code for the project transfer person.
Unity was not enough to solve the problem.
Resolved. thank you

**Comment by nathanmartz** [comment] 2017-06-21 05:54
Thanks for the help resolving this!

**Closed by nathanmartz** 2017-06-21 05:54 UTC
