### ISSUE TITLE
[Unity 2017.1.0f3 - iOS] Black Screen When Using Cardboard SDK

### ISSUE THREAD

**Issue by aschau** [googlevr/gvr-unity-sdk#661] opened 2017-07-18 23:38 UTC
After updating my projects to Unity 2017.1.0f3, my applications specifically on iOS no longer display anything in the scene besides the cardboard cutout. It only displays a black screen with the standard cardboard icons. 

I tested the Google Demo scene as well with nothing else loaded and it still has the same issue. I see no errors pop up in the console during run time when I load the scenes. I can still toggle the standard cardboard buttons like the back button which cancels out the cardboard and renders the scene like normal. 

Happens even in a completely empty scene with the SDK in a entirely new project.

Tested on iPhone 5 Version 10.3.2 (14F89).

![cardboard ios issue](https://user-images.githubusercontent.com/10569775/28344681-18b081c2-6bda-11e7-88da-9b654777df5e.jpg)

Fortunately, everything seems to be fine in Android and the X button seems to be back up and running.  Also, toggling VREnabled seems to no longer have any major issues, so thank you for that.

If anyone has the same issue and has been able to fix it, any feedback would be appreciated.

**Comment by Arakade** [comment] 2017-07-23 11:42
Are you using single pass rendering?  I'm having difficulties with that on Android.  Try disabling if so (purely for diagnostics).

**Comment by aschau** [comment] 2017-07-24 19:34
@Arakade I've been using multi-pass rendering for both Android and iOS. As of today, it is still only working for Android however.

**Comment by Arakade** [comment] 2017-07-24 19:51
Oh ok. Sorry I can't offer anything then -- no iOS here (yet). I assume there's nothing interesting in the logs? (E.g. Single pass failure gave me lots of GL state errors.)

**Comment by guardfromua** [comment] 2017-07-26 11:06
Same issue on Android

**Comment by maskedmous** [comment] 2017-07-26 15:02
Got this issue as well on both Android and iOS.
For android I received an error, for iOS nothing at all
`07-26 16:50:45.091: E/Unity(31317): (Filename: ./Runtime/GfxDevice/opengles/GfxDeviceGLES.cpp Line: 370)
07-26 16:50:45.110: E/Unity(31317): OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is not complete or incompatible with command`

**Comment by Arakade** [comment] 2017-07-26 18:43
Yep. That's the error I get too.
I made a little table of my results -- I'm on my mobile atm so can only link my frustrated tweet:

https://twitter.com/Arakade/status/886601019362344963

For me multi-pass was fine but single-pass not.

**Comment by CenekStrichel** [comment] 2017-07-28 12:46
Same trouble in iOS (multi pass). It is ok, when I use metal, but I need OpenGL2 due to another SDK. When you push Gear button (right up) > Switch VR > Skip .. it is ok. So we need some refresh as hack.

Any idea how simulate this hack?

**Comment by SamtheSpartan** [comment] 2017-08-11 21:43
Having the same problem. Pressing the gear, skipping and then returning to the app seems to fix things, but it's still unreleasable that way.

**Comment by dustinkerstein** [comment] 2017-08-22 23:18
Any updates on this? It's definitely a blocker for using 2017.1.0f3 on iOS.

**Comment by SamtheSpartan** [comment] 2017-08-22 23:49
No, still having this issue on iOS. I've voted on the issue in the Unity forums... we'll see if anyone responds!

**Comment by dustinkerstein** [comment] 2017-08-22 23:49
@SamtheSpartan, can you post the Unity forum bug link here? Thanks.

**Comment by SamtheSpartan** [comment] 2017-08-22 23:51
Here it is:

https://issuetracker.unity3d.com/issues/ios-cardboard-opengles-black-screen-on-vr-cardboard-builds-with-opengles2

**Comment by dustinkerstein** [comment] 2017-09-02 18:04
FYI - There definitely is an issue with Single Pass Rendering + GVR on Android Mali devices. I just posted a new issue specifically for that - #709

This issue (also cross listed in the GVR iOS SDK repo) is more specifically about the iOS issue.

**Comment by SamtheSpartan** [comment] 2017-09-05 16:10
@dustinkerstein I've tried to work around including Cardboard as a VR setting but obviously that's way more work than just including the native unity functionality. Seems like it's only happening on iOS still, have you found any fixes for it yet?

**Comment by dustinkerstein** [comment] 2017-09-05 16:13
@SamtheSpartan I haven't found any workarounds yet and there doesn't seem to be anyone working on it... I'm currently just planning on shipping with a warning (informing users how to get VR working) during the splash screen on iOS for the time being. Bad UX, but I really don't have any choice at the moment.

**Comment by SamtheSpartan** [comment] 2017-09-05 16:23
Daaaaaaaaaaaammit me too then. I assume you have to build it into the splash screen because any in-game canvases will just be composited into the cardboard viewer... thanks for the tip.

**Comment by dustinkerstein** [comment] 2017-09-05 16:26
Yah, I'm actually loading iOS with the "None" device first, showing the warning splash text, and then letting users switch into VR mode when they explicitly choose to.

**Comment by p12tic** [comment] 2017-09-07 09:45
This issue turned out to be caused by a bug on Unity side. It has already been fixed internally and will land to releases in 2-4 weeks unless something unexpected happens.

**Comment by CenekStrichel** [comment] 2017-09-07 09:48
@p12tic any chance to release it with upcoming patch?

**Comment by p12tic** [comment] 2017-09-07 10:00
Can't promise anything :-)

**Comment by dustinkerstein** [comment] 2017-09-07 11:56
Do you happen to know if it's in the 2017 beta release yet?

**Comment by alex-nac** [comment] 2017-09-13 17:20
I have the same problem :(

**Comment by amitchai** [comment] 2017-09-15 05:23
Same issue here. Black screen with stripes on iOS only. With GVR and without. Unity 2017.1.1f1

**Comment by gerardreches** [comment] 2017-09-19 11:21
@p12tic Is there a release date for the fix? We are waiting for it.

It's working correctly for me using an iPhone 6S, but not using an iPhone 5 (both of them iOS 10.3.3). For the iPhone 5 we need to use @CenekStrichel trick in order to see the scene.

**Comment by amitchai** [comment] 2017-09-19 12:05
I'm actually using iPad2... so old. but that's what I've got, and it was working till now.

**Comment by Zoriak22** [comment] 2017-09-24 22:29
The issue still exists, the latest Unity beta still not solved it. I can't publish my game on App Store because of this bug.

**Comment by dustinkerstein** [comment] 2017-09-25 14:23
And is also still reproducible on Unity 2017.1.1p3 - This is a breaking bug for me as well. Any update would be appreciated.

**Comment by fredsa** [comment] 2017-09-26 17:20
I was able to reproduce this using Unity 2017.1.1p3 (using an iOS 11.0 phone) by setting either **OpenGLES2** or **OpenGLES3** as the first Graphics API:

Full set of changes from a new / default Unity project to reproduce:
* **Player Settings > iOS > Other Settings > Virtual Reality Supported**: enabled
* **Player Settings > iOS > Other Settings > Virtual Reality SDKs**: Cardboard
* **Player Settings > iOS > Other Settings > Target minimum iOS Version**: 8.0 (was 7.0 by default)
* **Player Settings > iOS > Other Settings > Auto graphics API**: disabled
* **Player Settings > iOS > Other Settings > Graphics APIs**: OpenGLES2/3, …

**Comment by fredsa** [comment] 2017-09-26 17:21
Unity is working on getting the fix out for the aforementioned issue (thanks @SamtheSpartan):
> [Unity case 931397](https://issuetracker.unity3d.com/issues/ios-cardboard-opengles-black-screen-on-vr-cardboard-builds-with-opengles2) [IOS][CARDBOARD][OPENGLES][REGRESSION]
> _BLACK SCREEN ON VR CARDBOARD BUILDS WITH OPENGLES2_

**Comment by dustinkerstein** [comment] 2017-09-27 12:56
@fredsa It say's it's fixed in a future release but it's remained broken in the subsequent 2017.3 beta, 2017.2 RC, 2017.1 patch releases that are dated after it being marked as fixed. Should we just wait one more round of releases, or should we try to reach out to the folks on the Unity side to get more details?

**Comment by p12tic** [comment] 2017-09-28 16:25
Hi, as of now, the fixes are targeted to 5.6.4p2, 2017.1.2p1, 2017.2.0p1 and 2017.3.0b3.

**Comment by luizzenha** [comment] 2017-09-29 16:10
Hello everyone

I made a temporary solution.

Create a simple plugin and after Loaded Cardboard View and enabled the VR to call the native code below:

In Native Code: 

#import "UnityInterface.h"

-(void) myNativeMethod{
 UnityPause(1);
[NSTimer scheduledTimerWithTimeInterval:0.5f target:self selector:@selector(freeUnity) userInfo:nil repeats:NO];
}

-(void) freeUnity{
    UnityPause(0);    
}

It had worked for me,
Unity 2017.3.0b2
Xcode: 9.0
iPhone 5 with iOS 10.3.3

**Comment by AAKLebanon** [comment] 2017-10-02 20:57
Hi everyone. I have a similar issue to this, I am using unity 2017.1.1 and GVR-unity 1.7. 
However in my case, the game will crach, so I can see the black screen for 3 seconds and the game will crash. I tested this on iPhone 6 plus with iOS 10.3
However, I have found that the problem is in the GVR audio, so I deleted every reference in the demo scene to the GVR audio and the demo scene work now on my phone. I don't know if this issue is related to the issue mentioned in this thread, however I hope that it can help someone...

**Comment by dustinkerstein** [comment] 2017-10-05 18:41
FYI - Unity 2017.3.0b3 was just released today and does indeed fix this issue. Though I don't see it mentioned in the release notes.

**Comment by amitchai** [comment] 2017-10-07 18:35
Confirmed. Finally is working.

**Comment by fredsa** [comment] 2017-10-10 01:08
Great to hear 2017.3.0b3 fixes the issue.

Will leave this issue open a little longer, until the fix is back ported and released by the versions mentioned by @p12tic [above](https://github.com/googlevr/gvr-unity-sdk/issues/661#issuecomment-332890034).

**Comment by SelaO** [comment] 2017-10-19 18:22
I'm on unity 5.6.2f1 and GoogleVRForUnity_1.100.1 and it still happens...

**Comment by maskedmous** [comment] 2017-10-19 18:54
@SelaO thats because it is not fixed for 5.6.2f1. In the issue tracker a unity representative answered: 
> the fixes are targeted to 5.6.4p2, 2017.1.2p1, 2017.2.0p1 and 2017.3.0b3

So you should see the fix coming for 5.6.4p2

**Comment by SelaO** [comment] 2017-10-19 19:03
@maskedmous so what do you suggest I'll do? Use an older GVR version? I have to stay on 5.6.2f1.

**Comment by maskedmous** [comment] 2017-10-19 19:06
@SelaO I think this issue is unrelated to the SDK that is used. Rather something internally in Unity.
an upgrade to 5.6.4p2 should be do-able, is there something else broken in that release or is there some other reason you cannot upgrade to that version?

**Comment by lesmo** [comment] 2017-10-21 22:15
@SelaO I implemented @luizzenha solution successfully in my Unity 5.6.3p4 project, although using timers was not necessary. It was initially on v5.6.3f1 and I had to upgrade to see if it would solve this issue... it didn't.

Give that a try. Works great.

**Comment by ashunkhs** [comment] 2017-12-06 06:47
HI 
i have the same issue in iPhone 6 and iPhone 8 on Unity Version 2017.2.0p2 and GVR Version 0.9 .1 .

**Comment by rusmaxham** [comment] 2017-12-07 23:06
Try with the [latest patch release of 2017.2](https://unity3d.com/unity/qa/patch-releases?version=2017.2).  It worked for me, as do all of the latest patch released of 5.6 and 2017.x.

**Closed by rusmaxham** 2017-12-07 23:06 UTC
Labels: bug, Unity bug

**Comment by Flameshot** [comment] 2017-12-08 13:10
I don't know if I am asking it right but, does the GVR video player texture works on IOS? I made a scene with a 360 video but it seems that it is not rendered when I switch to that scene. It is just black screen.
I'm using the last release 2017.2.0p4 . Or anyone knows a hackfix to make that 360 video works with GVR on IOS?

**Comment by rusmaxham** [comment] 2017-12-08 18:10
No, the GvrVideoPlayerTexture is only formally supported on Daydream, tho it may work in Android Cardboard on some Android devices.

There are other video player texture plugins for Unity you can explore, 3rd party and Unity's [built-in video player](https://docs.unity3d.com/Manual/VideoPlayer.html) component.

**Comment by EdgarPironti** [comment] 2018-01-30 11:58
Hi all!
We are still having this issue, even with latest Unity version 2017.3, anyone else?

**Comment by amitchai** [comment] 2018-01-30 12:27
Remove the VR Graphic Jobs (Experimental)

**Comment by abelevtsov** [comment] 2018-02-10 19:16
"Remove the VR Graphics Jobs (Experimental)" - this helps

**Comment by josh-windsor** [comment] 2018-12-11 22:42
Same issue on 2018.2.16f1. Gonna have to deploy dev builds from now on :( Interestingly only occurs on one of my 2 projects with the same settings?

**Comment by maskedmous** [comment] 2018-12-12 06:39
Use metal rendering, open gles 3 is broken

**Comment by josh-windsor** [comment] 2018-12-13 14:30
So I couldn't fix this on Android or iOS even using metal. Ended up exporting the package to a new Unity project which fixed it. Some Unity bug I guess!

**Comment by danielmapar** [comment] 2019-02-28 11:36
Same here, using unit 2018.3.6f1 with both None and Cardboard + Metal. It gets locked in a black screen
