### ISSUE TITLE
Unity 2018.2.6f1 + GoogleVR 1.170.0 - crash while switching to Android platform or building apk

### ISSUE THREAD

**Issue by amirjaouani** [googlevr/gvr-unity-sdk#957] opened 2018-09-05 07:55 UTC
Summary:
Hello, I have a simple VR app and i use only a GVR Reticle pointer for select the buttons

Found using:
 * Google VR SDK version: 1.170.0
 * Unity version: 2018.2.6f1
 * Phone manufacturer, model, and O/S version: Windows 10
 * Viewer manufacturer & model: Windows 10

Steps to reproduce the issue:
 1. Create a new empty Unity 2018.2.6f1 project, then there are 2 cases:
 a. When i'm already switched to android Platform Unity will crash while importing the GoogleVR package
 b. In standalone Platform package will be imported succesfully, but it will crash during the android apk building or while switching to android platform

Workarounds:
I didn't find any.

Additional comments:

**Comment by rusmaxham** [comment] 2018-09-05 22:10
Can you file a bug with Unity through the Unity editor?

**Comment by rusmaxham** [comment] 2018-09-05 23:15
I'm unable to reproduce this on Mac or Win10 with those same versions of Unity and the GVR SDK.  Since this is a crash with Unity, I'm going to close it, as this issue should be filed with Unity.

**Closed by rusmaxham** 2018-09-05 23:15 UTC

**Comment by rusmaxham** [comment] 2018-09-13 16:35
related [issue 961](https://github.com/googlevr/gvr-unity-sdk/issues/961)

**Comment by rusmaxham** [comment] 2018-09-13 19:34
Have you filed a bug with Unity?  If so, could you let me know the bug #?

**Comment by rusmaxham** [comment] 2018-12-17 19:18
Can you file a bug with Unity?  If you can share a Unity issue # with me, I can escalate it.
