### ISSUE TITLE
Unity 5.6 iOS audio spatializer incompatible?

### ISSUE THREAD

**Issue by eternalflamez** [googlevr/gvr-unity-sdk#554] opened 2017-05-03 10:21 UTC
I am using the GoogleVR plugin for the GVR Audio spatializer plugin, which works fine in the editor and on Android, but when building for iOS the sound appears to be regular stereo. Furthermore, the logs show the following warning a dozen times:

`Audio source failed to initialize audio spatializer. An audio spatializer is specified in the audio project settings, but the associated plugin was not found or initialized properly. Please make sure that the selected spatializer is compatible with the target.`

This would normally suggest that the spatializer plugin isn't chosen in the audio settings, yet it has been set up correctly.

I am using Unity 5.6.0f3 on Mac OS and using the GVR sdk version 1.40 with iOS as the target platform.

**Comment by anokta** [comment] 2017-05-05 23:03
Thanks for catching this! 

The audio spatializer registration script on iOS was mistakenly removed during the last SDK update. This will be fixed via the v1.50 release.

**Comment by fredsa** [comment] 2017-10-23 16:16
Fixed in 1.70.0.

Duplicate of #618.

**Closed by fredsa** 2017-10-23 16:16 UTC
Labels: bug
