### ISSUE TITLE
Document how Asynchronous Reprojection works; Diegetic UI, not camera attached visible objects

### ISSUE THREAD

**Issue by dustinkerstein** [googlevr/gvr-unity-sdk#706] opened 2017-08-31 14:43 UTC
_Creating this new issue from the closed #700 as that went a little off topic._

I've read that the VR eye wobble (see [here ](https://drive.google.com/open?id=0B74otJbBFN-_TjFyQm96R0ZjcWs) for a video) that is caused by Asynchronous Reprojection is in fact by design. While I'm not sure I completely understand that (as to me Asynchronous Reprojection should really only have an effect when dropping frames), it definitely still causes some undesired wobbly behavior when you do one of the following:

1. Attach an object as a child of the camera (see the video linked above)
2. Synchronize the rotation of an object to the camera: 
`object.transform.rotation = Camera.current.transform.rotation;`
3. Synchronize the rotation of an object to the GVR head tracking: 
`object.transform.rotation = UnityEngine.VR.InputTracking.GetLocalRotation (VRNode.CenterEye);`
4. Synchronize the camera to the GVR head tracking for Magic Window Mode - See #700
`Camera.current.GetComponent<Transform> ().localRotation = UnityEngine.VR.InputTracking.GetLocalRotation (VRNode.CenterEye);`

This only happens when the "daydream" VR device is loaded. The "cardboard" device doesn't exhibit this because it doesn't enable Asynchronous Reprojection.

Is this wobbly behavior unavoidable in the above scenarios, or is this possibly a bug?

**Comment by fredsa** [comment] 2017-08-31 16:13
Asynchronous Reprojection is behaving as designed. The renderered stereo image is only intended to be viewed from within a VR headset, where Asynchronous Reprojection is designed to improve head tracking and user experience.

In general, you should not attach visible game objects to the VR driven camera (1) or attempt to synchronize visible game object transforms with the camera (2, 3). Headlocked game objects generally lead to a poor user experience and can be uncomfortable for users. Place visible objects in the world. Use _diegetic_ UI.

Since Asynchronous Reprojection is designed to be viewed in VR, it doesn't make sense for Magic Window (4).

To understand Asynchronous Reprojection, consider a user who is rotating their head:
* At the beginning of the frame, the device captures the current head pose, sets the camera transform, and then begins rendering the scene using the current camera pose.
* By the time the frame is done rendering, which is several milliseconds later, the head pose will have changed, since the user has continued to move their head while rendering was happening. 
* Asynchronous Reprojection changes how the rendered image is rendered out to the device display. It compensates for the difference between actual head pose at display time vs. the camera pose which was used to renderer the scene several milliseconds earlier.

**Comment by fredsa** [comment] 2017-08-31 16:15
Marking this issue as a documentation bug.

**Comment by dustinkerstein** [comment] 2017-08-31 16:16
Ok, that's a good explanation, but how would you propose building any type of UI like a HUD / visor?

**Comment by dustinkerstein** [comment] 2017-08-31 16:19
I guess it's a matter of "just don't do it"... Reading up on diegetic UX now.

It seems as though while objects attached to the camera may be bad practice in VR, Asynchronous Reprojection entirely precludes your ability to really even try it. Sound about right?

**Comment by fredsa** [comment] 2017-08-31 17:50
In practice, I would stay away from non-diegetic UI.

More theoretical answer (since you're interested):
To create head locked UI, you would need to somehow render that UI to the screen independently of the world image which is being reprojected. Your app would need to render two image layers and composite them together on the device screen: 1) the world view, which you would reproject, 2) head locked UI which you would not reproject. However, the ability to do this is not presently included in the SDK, nor is it provided by Unity through native integration. Hence, the "theoretical" answer.

**Comment by dustinkerstein** [comment] 2017-08-31 18:18
Thanks for the theoretical answer. I'll give that a try.

As you already noted by tagging this issue as a "documentation bug" - I definitely agree that it'd be a good idea to inform folks via the documentation that non-diegetic UI + Asynchronous Reprojection are essentially incompatible. I imagine this will come up again :)

**Comment by fredsa** [comment] 2017-08-31 18:59
Marked as documentation bug for:
- Document basic description of "how" async reprojection works & a little bit of "why"


https://developers.google.com/vr/distribute/daydream/design-requirements#UX-D2 covers head-locked objects being undesirable.

**Comment by nathanmartz** [comment] 2017-08-31 19:02
I'll take a stronger position than Fred and say that camera locked UI is
simply a bad idea in VR. It's uncomfortable and hard to use. If you need a
HUD, it's better to attach it to an object in world or display it on a 3d
visor.

**Comment by dustinkerstein** [comment] 2017-08-31 19:05
I'd even go further. With Asynchronous Reprojection, anything large like a HUD is going to be a broken wobbly mess :)

**Comment by dustinkerstein** [comment] 2017-09-18 18:45
I was just playing around with the new GVR 1.7 Performance HUD and noticed that it is headlocked but doesn't conflict with the Asynchronous Reprojection (ie. it's 100% stable). Would it not just be a better solution to have the workaround you proposed above, or something effectively similar, actually just be implemented "behind the scenes" in Unity's native integration for all objects that are intended to be in sync with the camera?

**Comment by chaosemer** [comment] 2018-08-13 21:31
Closing old issues. Like discussed above, head-locked UI is not good in VR.

**Closed by chaosemer** 2018-08-13 21:31 UTC
Labels: documentation bug
