### ISSUE TITLE
Unity Cardboard Applications crashing on Samsung S8 since update to Google VR Services

### ISSUE THREAD

**Issue by jules43** [googlevr/gvr-unity-sdk#695] opened 2017-08-23 07:59 UTC
Recently my family of Unity 5.6.x / Google Cardboard VR applications started crashing on start-up on Samsung S8 phone.

If I go into the Application manager in settings and disable "Google VR Services" then the crash no longer occurs.

This problems is being seen by a fair number of Unity developers and is discussed on this thread:

https://forum.unity3d.com/threads/galaxy-s8-crash.486911/

I have Gear VR builds of all the same applications and these are all working without the crash.

It is possible this issue is related to:
https://github.com/googlevr/gvr-unity-sdk/issues/684

**Comment by Ari3n** [comment] 2017-08-23 13:09
Simular issue here! Galaxy s8 . the app i develop starts with a Screen space menu, then when toggling to VrR mode the whole mobilefreezes and the app crashes. That crash even sets the wallpaper to the default one.

**Comment by fredsa** [comment] 2017-08-23 16:16
Duplicate of #671

**Closed** 2017-08-23 16:17 UTC
Labels: bug, duplicate

**Comment by jules43** [comment] 2017-08-23 16:33
This bug still occurs when the screen resolution is already WHQD+ and occurs prior to enabling VR mode.
