### ISSUE TITLE
Display cropped on S7 if not WQHD resolution GVR 1.60 Unity 2017.1.0f3

### ISSUE THREAD

**Issue by guneyozsan** [googlevr/gvr-unity-sdk#727] opened 2017-09-15 20:05 UTC
On S7 the display is cropped if resolution is not WQHD (sample image attached). This was working fine but after some update by Android OS, Unity or GVR, I don't know which one, it started displaying cropped after some point. View is fine with WQHD.
I'm on 2017.1.0f3 and GVR 1.60

![screenshot_20170915-225223](https://user-images.githubusercontent.com/19275187/30500927-2579bc26-9a69-11e7-997d-8477a3b0af74.png)

No idea if these issues are related:
https://github.com/googlevr/webvr-polyfill/issues/273
https://github.com/googlevr/gvr-unity-sdk/issues/421

**Comment by fredsa** [comment] 2017-09-15 20:20
Duplicate of #421

**Closed** 2017-09-15 20:20 UTC
Labels: bug, duplicate
