### ISSUE TITLE
Cardboard SDK 0.5.2 for Unity 5.2.2p4 - random head rotation on Android (Zeiss VROne)

### ISSUE THREAD

**Issue by xprojectvr** [googlevr/gvr-unity-sdk#120] opened 2015-11-20 11:27 UTC
Hi,
I'm using CardBoard Sdk v. 0.5.2 for Unity 5.2.2p4 and when i run my app on LG G3 (The Cardboard app is already set for Zeiss VROne) after some seconds the head is turnet randomly around the scene.
I made a new project with only the sdk and the demo scene inside to avoid any errors but the random rotation still happen.
Could you patch this issue?
Thanks

**Comment by smdol** [comment] 2015-11-24 01:50
So far we are unable to reproduce with LG G3.  Question:  Does this happen for apps downloaded from the Play Store too?

**Comment by xprojectvr** [comment] 2015-11-24 08:36
I don't know wich apps are compiled with the 0.5.2, if you can suggest me one for test I'll donwload and test it. I just recompiled my app with the 0.5.1 and I don't have the random head rotation issue but the performance and distortion features of the 0.5.2 are really much better.
I didn't publish my app on the play store, I make only local test.
Searching on the web i foud someone else with the same issue:
http://stackoverflow.com/questions/33690169/how-to-fix-google-cardboard-sdk-rotation-bug

**Comment by MiCkSoftware** [comment] 2015-11-24 11:38
Hi!

If it can help!


https://play.google.com/store/apps/details?id=com.software.mick.aaplus

Cheers !


Le mar. 24 nov. 2015 09:36, xprojectvr <notifications@github.com> a écrit :

I don't know wich apps are compiled with the 0.5.2, if you can suggest me
one for test I'll donwload and test it. I just recompiled my app with the
0.5.1 and I don't have the random head rotation issue but the performance
and distortion features of the 0.5.2 are really much better.
I didn't publish my app on the play store, I make only local test.
Searching on the web i foud someone else with the same issue:
http://
<http://stackoverflow.com/questions/33690169/how-to-fix-google-cardboard-sdk-rotation-bug>
stackoverflow.com
<http://stackoverflow.com/questions/33690169/how-to-fix-google-cardboard-sdk-rotation-bug>
/questions/33690169/
<http://stackoverflow.com/questions/33690169/how-to-fix-google-cardboard-sdk-rotation-bug>
how-to-fix-google-cardboard-sdk-rotation-bug
<http://stackoverflow.com/questions/33690169/how-to-fix-google-cardboard-sdk-rotation-bug>

—
Reply to this email directly or view
<https://github.com/googlesamples/cardboard-unity/issues/120#issuecomment-159195569>
<https://github.com/googlesamples/cardboard-unity/issues/120#issuecomment-159195569>
it
<https://github.com/googlesamples/cardboard-unity/issues/120#issuecomment-159195569>
on
<https://github.com/googlesamples/cardboard-unity/issues/120#issuecomment-159195569>
GitHub
<https://github.com/googlesamples/cardboard-unity/issues/120#issuecomment-159195569>.<img
src="
https://ci6.googleusercontent.com/proxy/Zs9wMpW_B8SGDHkKc7x1TPnBheFLuneoa_fuHsp2UjZMpBo-ant-FdmV89KI_f8jrM7ad6n5L5ycI1gWVAmmpbJSfvkEZ2t8WOqdZWuM3JqUFr3V8JdLtg-9Iff9sZIrZvna83b6r8-Uk4DCFuFmoXl6TpPAmw=s0-d-e1-ft#https://github.com/notifications/beacon/AMIc3EVU3try_CGRd6qaLyUeeNAP-PTsks5pJBkAgaJpZM4GmTRr.gif
">

**Comment by schitzN** [comment] 2015-11-27 10:23
Hello,

we got the exact same problem here!

Unity 5.2.2f1
CardBoard Sdk v. 0.5.2
LG G3 - fully updated

There are random jumps of the camera rotation. I also have these jumps with other VR apps - for example the AirPano App..

The "Cardboard Demos App" works perfectly thou... Also https://play.google.com/store/apps/details?id=com.software.mick.aaplus works very good!

There are more guys reporting similar bugs out there, there is even one fix, which unfortunatelly does not work for me and also uses deprecated code: https://karma.neocities.org/cardboard/cardboard.html

**Comment by smdol** [comment] 2015-12-01 16:21
OK, I'll ask our QA team to try AirPano on their LG G3.  Thanks for the tip, it's very helpful!

**Comment by smdol** [comment] 2015-12-03 20:09
So with AirPano on our in-house LG G3 we do see a weird gyro effect:  if you tilt the phone sideways and then back, the world has tilted about 20 degrees up or down.  This only happens a few times then stops.  Is this similar to way you are seeing?

**Comment by Forux** [comment] 2015-12-07 22:38
I have on lg g3 stable repro of random camera rotation on SDK 0.52, in previous version camera resets to the start position. It looks like it depends on fps, lower fps - more random camera rotations.

**Comment by schitzN** [comment] 2015-12-08 17:10
@smdol yes we do see a similar effect too, but this is another issue and not the one i mentioned. Additionally to these weird tilts, we have these jumps described before.

I also have to add, that we now have multiple lg g3 units here. All have the same issue, but most of them do work for some minutes. But when the app is running for some time and the device gets hot, these random camera rotation jumps start.

We also tested the exact same apk on other devices (OnePlus Two, OnePlus One, MotoX) and the app is working perfectly on all other devices - even when the app is running for quite some time and the device gets warmer.

**Comment by tb9jen** [comment] 2015-12-15 16:28
I am also having this exact problem on an LG G3 with 0.5.2 using Unity 5.3.0f4. It goes about 20-30 seconds between jumps. It does appear to be fps related (drops to 20-30 and the jumps occur more frequently).

**Comment by smdol** [comment] 2016-01-14 03:29
We've made progress in tracking this down, though unfortunately I don't think it is fixed in the latest release, v0.6, yet.  For some reason on the LG G3 phone, the sensor time stamps can jump a lot for the gyro.  Too big a jump apparently causes the head tracking code to reset the orientation.  So that's under investigation.

**Comment by bmasala** [comment] 2016-01-15 07:15
Same issue here, is this isolated to the LG G3?

**Comment by smdol** [comment] 2016-01-18 21:48
LG G3 seems especially prone to this issue, but I don't know for sure if it is the only phone that it happens to.

**Comment by Nodrap** [comment] 2016-09-14 08:32
This issue is still a big problem for me and my LG G3 phone. Can be reduced for a while with a reboot but always comes back to a point where you cannot do any VR experiences. Am developing one myself using the latest Untiy and GoogleVR and the problem is still there. Is a real shame too as the G3 is a great phone for VR as it has a really high resolution screen.

**Comment by vitorbalbio** [comment] 2016-10-24 21:59
There's no oficial fix for this yet?
You guys can get some inspiration here: https://karma.neocities.org/cardboard/cardboard.html

**Comment by chaosemer** [comment] 2017-02-16 23:06
Is this still an issue? Right now I'm closing this, but if this is still an issue, please reopen and comment.

**Closed by chaosemer** 2017-02-16 23:06 UTC
