### ISSUE TITLE
Android build error with Unity 2017.2.0b4 and GVR 1.60

### ISSUE THREAD

**Issue by guneyozsan** [googlevr/gvr-unity-sdk#669] opened 2017-07-29 17:17 UTC
I get the following errors if I try to build for Android with Unity 2017.2.0b4 and GVR 1.60.

```
Error: Duplicate file(s) in apk: 'D:\PROJECT_PATH\Temp\StagingArea\android-libraries\gvr\libs'

UnityEngine.GUIUtility:processEvent(Int32, IntPtr)

```

```
CommandInvokationFailure: Failed to build apk.
C:/Program Files/Java/jdk1.8.0_131\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="C:/Users/Guney/AppData/Local/Android/sdk\tools" -Dfile.encoding=UTF8 -jar "C:\Program Files\Unity 2017.2.0b4\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Error: Duplicate file(s) in apk: 'D:\PROJECT_PATH\Temp\StagingArea\android-libraries\gvr\libs'
]
stdout[

]
exit code: 255
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandInternal (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidSDKTools.RunCommandSafe (System.String javaExe, System.String sdkToolsDir, System.String[] sdkToolCommand, Int32 memoryMB, System.String workingdir, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEngine.GUIUtility:processEvent(Int32, IntPtr)
```

**Comment by tedruxpin** [comment] 2017-08-02 18:10
Hi, have you tried deleting the Temp and Library folders and rebuilding the project from scratch?

**Comment by VasilOrlinov** [comment] 2017-08-06 16:46
i get the same error with 2017.2.0b5 and gvr 1.70. Deleting temp and library folders doesnt fix it.

**Comment by joejo-unity** [comment] 2017-08-08 16:47
Can you please file a bug with Unity with a small repro project and reply with the case id here?

**Comment by davtamay** [comment] 2017-08-19 17:02
Same error, 2017.2.0xb6 and gvr 1.70... previous solutions involved getting rid of a text file within the android plugins folder, but I am at a loss about what to get rid off now for a solution...

**Comment by davtamay** [comment] 2017-08-20 21:07
Solved by modifying x86 plug-in file under libs in inspector. Just changed android Armv7 to x86 in android setting. Contribution goes to:

https://forum.unity3d.com/threads/cannot-build-for-android-found-plugins-with-same-names-and-architectures-dear-god.431203/

**Comment by ichabodcole** [comment] 2017-09-04 09:24
FYI, also hitting this issue on 2017.2.0b9 with GVR 1.70, seems to be related to the libaudiopluginbrunity files in Plugins/Android/libs. I was not able to set the x86 lib to x86 in the platform settings do to the error noted below, and even deleting that file still caused the build failure noted above. I eventually just unchecked all of the libraries included platforms for both files and that fixed the problem.

```
Failed to parse value ('AnyCPU') for CPU, platform: Android, type: UnityEditor.AndroidPluginImporterExtension+AndroidPluginCPUArchitecture. Default value will be set 'ARMv7'
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

Dev Specs:
Windows 10
GVR 1.70
Unity 2017.2.b09
Zenphone AR

**Comment by fredsa** [comment] 2017-09-04 15:45
Looks like Unity 2017.2 beta and GVR SDK are both including the same library.

**Comment by joejo-unity** [comment] 2017-09-04 17:47
I believe we ship this library as part of the Unity 2017.2 release. Google should be aware of this and I would hope the SDK would handle checking for this.

+ Micheal who was responsible for getting this into 2017.2 on Unity’s side.

**Comment by fredsa** [comment] 2017-09-04 19:43
To workaround this conflict when using GVR SDK 1.70 or earlier with Unity 2017.2 or later:

1. From the **Project** window select
   _GoogleVR/Plugins/Android/libs/**armeabi-v7a**/libaudioplugingvrunity_
1. Uncheck **Android** in the Inspector window and click **Apply**
1. From the **Project** window select
   _GoogleVR/Plugins/Android/libs/**x86**/libaudioplugingvrunity_
1. Uncheck **Android** in the Inspector window and click **Apply**

**Comment by fredsa** [comment] 2017-09-04 19:45
Removing the 'Unity bug' label as the Unity behavior is intentional. This conflict will be fixed in an upcoming GVR SDK release.

**Comment by ShacharWeis** [comment] 2017-10-15 21:54
This saved my ass, after HOURS of pulling my hair out. I can confirm this is still a problem with 2017.2.0f1

**Comment by rusmaxham** [comment] 2017-10-16 18:18
This is now fixed in the publicly released 2017.2.0f3.

**Comment by Claytonious** [comment] 2017-10-16 18:18
Still an issue on 2017.3b4, but now further complicated by a new build failure if you simply use the workaround of unchecking the Android platform on both of these libs. The error is that the Gvr Audio Renderer effect is failing to find the native libs it wants (presumably these guys that we've disabled to get around the original error). Trying to workaround this now by also removing the GvrAudioMixer from Resources/ folder of gvr sdk...

**Closed by rusmaxham** 2017-10-16 18:18 UTC
Labels: bug

**Comment by rusmaxham** [comment] 2017-10-16 18:32
I'm unable to reproduce this issue with 2017.3b4.  Are you able to reproduce this issue with the GVRDemo in the GoogleVR SDK on 2017.3b4?  If so, what is the specific failure mode you're seeing?

**Comment by diramazioni** [comment] 2017-10-31 09:23
I still have this issue using 2017.3.0b1 that is the latest release under linux and GoogleVRForUnity_1.100.1 using the GVRDemo scene
I can build using the workaround described by @fredsa.
What you mean by "specific failure mode" how can I help out?

**Comment by rusmaxham** [comment] 2017-11-02 16:47
By failure mode, I mean how do you know it is failing?  What message?  Can you share all of the details of the error log?

Can you try with the latest 2017.3 beta 7?
