### ISSUE TITLE
Crash when using spatial audio - iOS

### ISSUE THREAD

**Issue by crtq** [googlevr/gvr-unity-sdk#740] opened 2017-10-04 07:38 UTC
Yo guys I always get a crash of the iOS app when I try to upload a scene with spatial audio (even demo scenes with room audio). Has anybody else had this? Any workaround? 
I'm on Unity 2017 - gvr sdk 1.70 - iphone 6 version 11.0.1.

These are the errors I get:

```
2017-10-04 09:35:52.099415+0200 squashy[5546:1872334] [DYMTLInitPlatform] platform initialization successful

2017-10-04 09:35:52.295796+0200 squashy[5546:1872142] -> registered mono modules 0x1023fba70
-> applicationDidFinishLaunching()
Player data archive not found at `/var/containers/Bundle/Application/2D87075C-0804-43BF-AE11-E88C500847E7/squashy.app/Data/data.unity3d`, using local filesystem
2017-10-04 09:35:52.710108+0200 squashy[5546:1872142] Metal GPU Frame Capture Enabled
2017-10-04 09:35:52.711357+0200 squashy[5546:1872142] Metal API Validation Disabled
2017-10-04 09:35:52.904429+0200 squashy[5546:1872142] [MC] Lazy loading NSBundle MobileCoreServices.framework
2017-10-04 09:35:52.906645+0200 squashy[5546:1872142] [MC] Loaded MobileCoreServices.framework
2017-10-04 09:35:52.955131+0200 squashy[5546:1872142] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2017-10-04 09:35:53.041489+0200 squashy[5546:1872142] refreshPreferences: HangTracerEnabled: 0
2017-10-04 09:35:53.041619+0200 squashy[5546:1872142] refreshPreferences: HangTracerDuration: 500
2017-10-04 09:35:53.041693+0200 squashy[5546:1872142] refreshPreferences: ActivationLoggingEnabled: 0 ActivationLoggingTaskedOffByDA:0
-> applicationDidBecomeActive()
GfxDevice: creating device client; threaded=1
Initializing Metal device caps: Apple A8 GPU
Initialize engine version: 2017.1.1f1 (5d30cf096e79)
2017-10-04 09:35:54.349028+0200 squashy[5546:1872142] INFO [vr/gvr/capi/src/gvr.cc:109] Initialized GVR version 1.60.0
=================================================================
Main Thread Checker: UI API called on a background thread: -[UIApplication delegate]
PID: 5546, TID: 1872311, Thread name: (none), Queue name: NSOperationQueue 0x1c023d2a0 (QOS: UNSPECIFIED), QoS: 0
Backtrace:
4   squashy                             0x00000001012fdec4 UnityCurrentOrientation + 60
5   squashy                             0x00000001012eb980 __UnityCoreMotionStart_block_invoke + 108
6   Foundation                          0x0000000182322310 <redacted> + 16
7   Foundation                          0x00000001822629e4 <redacted> + 72
8   Foundation                          0x0000000182252620 <redacted> + 848
9   libdispatch.dylib                   0x00000001812dd048 <redacted> + 16
10  libdispatch.dylib                   0x00000001812e46c8 <redacted> + 288
11  libdispatch.dylib                   0x00000001812dd048 <redacted> + 16
12  libdispatch.dylib                   0x00000001812e46c8 <redacted> + 288
13  libdispatch.dylib                   0x00000001812e4574 <redacted> + 104
14  Foundation                          0x0000000182323fe8 <redacted> + 376
15  libdispatch.dylib                   0x00000001812dd048 <redacted> + 16
16  libdispatch.dylib                   0x00000001812e53d4 <redacted> + 428
17  libdispatch.dylib                   0x00000001812e3cd4 <redacted> + 604
18  libdispatch.dylib                   0x00000001812ea1c8 <redacted> + 596
19  libdispatch.dylib                   0x00000001812e9f10 <redacted> + 120
20  libsystem_pthread.dylib             0x0000000181583130 _pthread_wqthread + 1268
21  libsystem_pthread.dylib             0x0000000181582c30 start_wqthread + 4
2017-10-04 09:35:54.605802+0200 squashy[5546:1872311] [reports] Main Thread Checker: UI API called on a background thread: -[UIApplication delegate]
PID: 5546, TID: 1872311, Thread name: (none), Queue name: NSOperationQueue 0x1c023d2a0 (QOS: UNSPECIFIED), QoS: 0
Backtrace:
4   squashy                             0x00000001012fdec4 UnityCurrentOrientation + 60
5   squashy                             0x00000001012eb980 __UnityCoreMotionStart_block_invoke + 108
6   Foundation                          0x0000000182322310 <redacted> + 16
7   Foundation                          0x00000001822629e4 <redacted> + 72
8   Foundation                          0x0000000182252620 <redacted> + 848
9   libdispatch.dylib                   0x00000001812dd048 <redacted> + 16
10  libdispatch.dylib                   0x00000001812e46c8 <redacted> + 288
11  libdispatch.dylib                   0x00000001812dd048 <redacted> + 16
12  libdispatch.dylib                   0x00000001812e46c8 <redacted> + 288
13  libdispatch.dylib                   0x00000001812e4574 <redacted> + 104
14  Foundation                          0x0000000182323fe8 <redacted> + 376
15  libdispatch.dylib                   0x00000001812dd048 <redacted> + 16
16  libdispatch.dylib                   0x00000001812e53d4 <redacted> + 428
17  libdispatch.dylib                   0x00000001812e3cd4 <redacted> + 604
18  libdispatch.dylib                   0x00000001812ea1c8 <redacted> + 596
19  libdispatch.dylib                   0x00000001812e9f10 <redacted> + 120
20  libsystem_pthread.dylib             0x0000000181583130 _pthread_wqthread + 1268
21  libsystem_pthread.dylib             0x0000000181582c30 start_wqthread + 4
2017-10-04 09:35:57.272729+0200 squashy[5546:1872349] [BoringSSL] Function boringssl_context_get_peer_sct_list: line 1754 received sct extension length is less than sct data length
UnloadTime: 11.336875 ms
(lldb) 
```

**Comment by rusmaxham** [comment] 2017-10-04 17:45
This is a duplicate of https://github.com/googlevr/gvr-unity-sdk/issues/665.  See that issue for a workaround until the proper fix is pushed live.

**Closed by rusmaxham** 2017-10-04 17:45 UTC
