### ISSUE TITLE
Display wrong when I change the resolution of Android 7.0

### ISSUE THREAD

**Issue by clarkehe** [googlevr/gvr-unity-sdk#654] opened 2017-07-14 01:48 UTC
I tried using Samsung S7.  The default resolution is 2560x1440.  When I change the resolution to 1920x1080, cardboard apps run with problem (see the screenshot below).  I tested with Gvr ndk (Initialized GVR version 1.60.1) treasurehunt sampe and unity gvr demo. Both have this issue.

![bug1](https://user-images.githubusercontent.com/8831805/28194665-67d17960-6878-11e7-821a-7b8cdaa3f136.png)

![bug2](https://user-images.githubusercontent.com/8831805/28194716-b3a78ed8-6878-11e7-9baa-c1a7933601a1.png)

**Comment by nathanmartz** [comment] 2017-07-14 17:37
What version of Unity and our SDK are you using?

**Comment by clarkehe** [comment] 2017-07-15 02:11
@nathanmartz  Unity5.6.0f3 and GVR SDK 1.4

**Comment by VIRTUALITYREPOSI** [comment] 2017-08-15 07:05
Unity 2017.1.0f3 and GVR SDK 1.7

**Comment by parkitny** [comment] 2017-08-23 11:49
I have the same issue. I have tried to compile with gvr sdk 1.8, 1.6, 0.9, 0.7. The issue occurs with all apps ive compiled that use the gvr sdk to render. It seems like the scene renders to the max device resolution and the viewport crops out a section at the current configured device resolution. Hence resulting in a zoomed in effect. It was fine on android 6.0 on my galaxy S7 but upgrading to android 7, and setting the device resolution to any setting lower than WQHD triggers the issue. Running with WQHD ( full resolution) does not cause any problems and apps run as expected. Hope this will be fixed soon.

**Comment by fredsa** [comment] 2017-08-23 16:07
Duplicate of #421

**Closed** 2017-08-23 16:13 UTC
Labels: bug, duplicate
