### ISSUE TITLE
The screen ain't right

### ISSUE THREAD

**Issue by KaiPar** [googlevr/gvr-unity-sdk#515] opened 2017-03-29 03:25 UTC
![image](https://cloud.githubusercontent.com/assets/26135296/24437185/505bed52-145d-11e7-9a41-31573c38fb03.png)
 Can anyone tell me how shall i fix it?

Thank you.

**Comment by miraleung** [comment] 2017-03-29 03:26
This has been fixed in our current release (1.30) - the root cause was described in #451.

**Closed by miraleung** 2017-03-29 03:26 UTC
