### ISSUE TITLE
video surface ignore the rotate by setVideoLocationTransform 

### ISSUE THREAD

**Issue by wangxiaogangan** [googlevr/gvr-unity-sdk#776] opened 2017-11-09 06:22 UTC
https://github.com/googlevr/gvr-unity-sdk/issues/767 not fixed

thanks in first, i try your method to calc matrix for "setVideoLocationTransform"

the surface translate its position but still ignore rotate like below pic

![screenshot_20171108-202807](https://user-images.githubusercontent.com/8535634/32591035-6dfa99ba-c558-11e7-8c59-e5e3125f2c73.png)
![screenshot_20171108-202654](https://user-images.githubusercontent.com/8535634/32591036-6eea95be-c558-11e7-861a-342cfedf80bd.png)

the first pic show video surface init pos & surface look at camera， 
the sec pic show camera rotate a degree & surface translate its pos but surface still look at (0, 0, -1), dont change surface rotation, the ui panel look at camera & surface not has same rotation compare with ui

i think its a bug for rotation, please give me some advise~~~ its perfect if demo exists ??

**Comment by rusmaxham** [comment] 2017-11-09 17:44
Dupe of https://github.com/googlevr/gvr-unity-sdk/issues/767

**Closed by rusmaxham** 2017-11-09 17:44 UTC
