### ISSUE TITLE
GvrViewer.Instance.ShowSettingsDialog() Does nothing

### ISSUE THREAD

**Issue by dill0wn** [googlevr/gvr-unity-sdk#319] opened 2016-09-16 20:17 UTC
I'm on GoogleVR v0.8.1. EDIT: I've also tried 0.9.1

The phone and app are in portrait mode.  I have a scene that is empty except for a button.  When I click that button, the following executes:

``` csharp
GvrViewer.Create();
GvrViewer viewer = GvrViewer.Instance;
viewer.VRModeEnabled = false;
viewer.BackButtonMode = GvrViewer.BackButtonModes.Off;
viewer.EnableAlignmentMarker = false;
viewer.EnableSettingsButton = false; 
viewer.ShowSettingsDialog();
```

... and nothing happens.  I expect the GoogleVR settings scanner/dialog to appear.

I'm testing on an iPhone 6+ running iOS 10.0.1, built with Unity 5.3.4f1, and XCode 8. I've tested with graphics API set to Auto, as well as only OpenGLES2.

Additionally, instead of immediately calling `ShowSettingsDialog()`, I have also tried starting a coroutine that waits a few seconds then tries to open settings.

Is opening the settings dialog this way just not supported anymore?

**Comment by dill0wn** [comment] 2016-10-03 19:28
I've updated and tried this with 1.0.0, with identical results.  Am I doing something wrong?  I've seen it on both iOS and Android.

**Comment by nathanmartz** [comment] 2016-10-04 04:25
Hi. This is a regression for the 1.0 SDK due to our work on the native integration for Unity. We're working on restoring it in our next version.

**Comment by nathanmartz** [comment] 2016-10-04 04:25
Actually, I should be more specific. The ShowSettingsDialog() part will be fixed. We will no longer allow developers to disable standard "aperature" including the back button, alignment line, and gear icon.

**Comment by dill0wn** [comment] 2016-10-04 04:46
Awesome, thanks!  I guess I'll leave this open until then?

**Comment by miraleung** [comment] 2016-10-07 18:31
@dill0wn, is the gear button on iOS working for you, when the phone is in landscape? That calls ShowSettingsDialog() and it's doing the right thing for me (Unity 5.3.3, plugin v1.0).

**Comment by dill0wn** [comment] 2016-10-08 17:52
Yes, for whatever reason the gear icon works fine.  I only have issues if cardboard is instantiated, vr is disabled, and i try to manually call ShowSettingsDialog() with my code.

**Comment by MattFedo** [comment] 2016-12-06 16:44
So how is this coming?  Do we have something that will launch the 'pairing' from something other than the settings button in VR mode?  I think it would be worth the time to have something available in which we could launch the pairing from our own settings screen that is in screen space and not world space.

**Closed** 2017-04-19 20:33 UTC
