### ISSUE TITLE
App crash on loading VR view on latest devices (Samsung Note 8, Samsung 8, 8+) with Android 7.0, 7.1, 7.1.1

### ISSUE THREAD

**Issue by aAAC** [googlevr/gvr-unity-sdk#731] opened 2017-09-18 22:06 UTC
I'm using
Unity2017.2.0b11
GVR Unity v1.70.0

As soon app enters in VR mode it crashes on Samsung Note 8 and stucks on S8, can't load VR veiw

We've tried to switch back to Unity 5.6.3 + GVR 0.8, It fixes the issue but video start playing in upside down and also app doesn't goto landscape, always stucks to portrait mode only. 

Have added this line to change the orientation but it has started crashing again.
`Screen.orientation = ScreenOrientation.LandscapeLeft;`

**Comment by tedruxpin** [comment] 2017-09-19 17:24
Hello aAAC, can you attach a crash log?  Thank you!

**Comment by guneyozsan** [comment] 2017-09-19 17:53
You can also check this topic to see if WQHD fixes the crash:
https://github.com/googlevr/gvr-unity-sdk/issues/671

**Comment by aAAC** [comment] 2017-09-19 20:26
@tedruxpin please find the attached crash log
[logs.txt](https://github.com/googlevr/gvr-unity-sdk/files/1315717/logs.txt)


@guneyozsan , But I've to upload for general public, how everyone will be switching to WQHD?

**Comment by guneyozsan** [comment] 2017-09-21 11:35
@aAAC yes that's another problem. I noted the issue to help you see if it is the same problem or not.

**Comment by fredsa** [comment] 2017-09-21 21:01
If the "crash" (actually, unexpected app close immediately after launch) does not happen when the device is set to WQHD+ resolution (_Settings > Display > Screen resolution > **WQHD+** > APPLY_), then this is a duplicate of #671.

Marking this issue as a duplicate. However, if the issue does not go away with WQHD+ resolution, please feel free to reopen.

**Closed by fredsa** 2017-09-21 21:01 UTC

**Comment by aAAC** [comment] 2017-09-21 22:26
@fredsa 
I'll uploading this build for general public so I'll convey to everyone to goto settings and change their  resolutions? 

Also I've tried with all three available resolutions in Screen Resolutions but it was still crashing on Note 8.

I've downgraded my project to Unity 5.6.3 and gvr 0.7 and its working now :)

**Comment by fredsa** [comment] 2017-09-22 00:19
@aAAC If using WQHD+ resolution (_Settings > Display > Screen resolution > **WQHD+** > APPLY_) does not fix the issue for you with the that latest Unity and Google VR SDK, then please file a new issue and include a crash logs (`adb logcat`).
