### ISSUE TITLE
Sometimes "GvrReticlePointer" it gets lost when the camera moves (with an "Autowalk" script)

### ISSUE THREAD

**Issue by amianperez** [googlevr/gvr-unity-sdk#977] opened 2018-11-05 08:04 UTC
Good morning,
I have a virtual tour of a museum and I want to use object detection to open an information poster. The idea is that the pointer "GvrReticlePointer" is activated when it is some distance from the object, this is achieved by changing the value of the parameter "Max Reticle Distance" to 2 or 3.
The problem is that sometimes it works all the time but others do not the object of the "GvrReticlePointer" is activated and I can not isolate the problem because the deactivation is completely random.
Any idea where the problem may come from? I think it's a bug because I can not find a pattern of the error's appearance. Thank you very much in advance.

Found using:
 * GVR SDK for Unity v1.170.0
 * Unity 2018.2.12f
 * It happens on MacOs High Sierra and on a Samsung S8 (Android 8)
![duda](https://user-images.githubusercontent.com/15077751/47985344-a1b02200-e0d9-11e8-8661-b71b65be401a.jpg)

**Comment by chaosemer** [comment] 2018-11-06 00:21
Could you please share your project with us so we can investigate?

**Comment by amianperez** [comment] 2018-11-06 15:03
Yes, i will prepare a project for share ;)...
For the moment I have been able to solve it by making desactivate and activate "GvrReticlePointer" script inside GameObject "GvrReticelPointer" every time you start walking.
In this way, the "GvrReticlePointer" is reset and works well again.
For now it is the best solution I could find

**Comment by mansoor090** [comment] 2018-11-06 16:12
Hey Amian, https://github.com/JuppOtto/Autowalk-for-Google-VR-SDK-with-Unity . are you using this script?

**Comment by chaosemer** [comment] 2018-11-07 21:48
I'm glad you have a workaround, but we would still like a repro project so we can investigate the issue.

**Comment by amianperez** [comment] 2018-11-08 07:33
Of course, I have the project ready to share, I have been finishing the original project and I did not have time. Where do I share it?

**Comment by amianperez** [comment] 2018-11-08 07:33
> I'm glad you have a workaround, but we would still like a repro project so we can investigate the issue.

Of course, I have the project ready to share, I have been finishing the original project and I did not have time. Where do I share it?

**Comment by chaosemer** [comment] 2018-11-09 16:33
Thanks for the PM, I got the project you shared and will attach it to the bug in our internal database.

**Comment by ddrocco** [comment] 2019-01-18 23:19
Hi, I managed to fix this in my own environment.  It looks like the "deactivation" problem is being caused by the GvrPointerPhysicsRaycaster occasionally getting into a state of colliding with the VR_Player.  GvrPointerPhysicsRaycaster is currently set to collide with EVERYTHING.  When I disabled a layer from the GvrPointerPhysicsRaycaster's RaycasterEventMask and assigned the VR_Player to that disabled layer, I was unable to replicate the bug and it appears to be working.

Closing this since there doesn't seem to be any action needed on our part.  Please reopen the bug if you have any more issues!

**Closed by ddrocco** 2019-01-18 23:19 UTC
