### ISSUE TITLE
Camera drifts towards the left

### ISSUE THREAD

**Issue by s1mar** [googlevr/gvr-unity-sdk#338] opened 2016-10-04 04:48 UTC
Hello,

the camera drifts towards the left pretty fast on its own,with the phone lying flat.
It happens almost 9/10 times.
Also the plugin(1.0.0) is running in compatibility mode even though I have unity 5.4.

**Comment by s1mar** [comment] 2016-10-04 07:02
Update: on some phones this problems doesn't exist,what might be causing the problem

**Comment by s1mar** [comment] 2016-10-04 07:32
Update :After removing the app completely,reinstalling it and re calibrating my phone sensors,the app works fine BUT after a few usages the bug again appears

**Comment by s1mar** [comment] 2016-10-04 10:06
Update:Nope,the above stated technique isn't even working anymore,I'm stuck with a drifting camera

**Comment by nathanmartz** [comment] 2016-10-04 15:29
Hi, s1mar. Drift is a known issue on some phones. The amount of drift and repro steps depend on the specific hardware. We'll be making steady improvements to drift correction in cardboard, but it's hard to simply "fix" this for all devices. I'm closing this as we have other open bugs on this issue.

**Closed by nathanmartz** 2016-10-04 15:29 UTC

**Comment by s1mar** [comment] 2016-10-05 04:56
Okay but about the other thing,why does the plugin run in compatibility mode even though I have unity 5.4

**Comment by nathanmartz** [comment] 2016-10-05 05:45
That compat message has an error. It should say that you need to compat
mode for anything older than the native integration which happens to
include the mainline unity 5.4.

**Comment by s1mar** [comment] 2016-10-05 07:52
Hi Nathan,I updated to the latest Beta version of unity (5.5.0b6) and I still get that error
![gvrbug](https://cloud.githubusercontent.com/assets/16931768/19105249/b9b55998-8afe-11e6-8bd1-b17ce873d348.png)

**Comment by nathanmartz** [comment] 2016-10-05 15:46
Like I said, the problem is in the message. This appears on any version of unity that isn't the technical preview w/ Daydream integration. If you imported the compat packages, you can safely ignore it.

**Comment by miraleung** [comment] 2016-10-05 22:56
@s1mar The Daydream integration version is 5.4.1f1-GVR7.1, available [here](https://unity3d.com/partners/google/daydream).
