### ISSUE TITLE
HeadPhones issue !!

### ISSUE THREAD

**Issue by semangu** [googlevr/gvr-unity-sdk#185] opened 2016-03-03 00:00 UTC
someone knows because when I plug in my headphones begins to self-center the image when I look at the sides ?

I have tried several headphones and all this happening to me .

Thank you so much.

**Comment by semangu** [comment] 2016-03-07 13:21
Nothhing?  It,s really strange. The experiencie go Will, but when i plug in my head phones,  the game  random restar the gyro to start position.

Please help me.

**Comment by justinwasilenko** [comment] 2016-03-07 13:55
Do you have the Sony Xperia? I have heard a few users complain of this also
with Sony phones.

On Mon, Mar 7, 2016 at 2:21 PM semangu <notifications@github.com> wrote:

> Nothhing? It,s really strange. The experiencie go Will, but when i plug in
> my head phones, the game random restar the gyro to start position.
>
> Please help me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/googlesamples/cardboard-unity/issues/185#issuecomment-193245603>
> .
>
-- 
Justin Wasilenko

*End Space VR*
http://endspacevr.com

Like the Facebook page:
https://www.facebook.com/endspacevr

**Comment by semangu** [comment] 2016-03-07 13:56
Yes, i have a Sony Xperia z3, thanks!!

**Comment by semangu** [comment] 2016-04-10 18:10
anybody know how to fix it,when i plug in my earphones the VR image auto recenter if not move the device.

Please help !!

**Comment by smdol** [comment] 2016-04-10 20:19
I'll ask our QA team to reproduce if they can.  Is Sony Xperia z3 the only phone you have seen this happen on?

**Comment by semangu** [comment] 2016-04-10 23:03
sorry, i haven't other android device now.

**Comment by semangu** [comment] 2016-04-11 11:29
But i try the same unity project with other VR plugin (LC RV Kit) and work correctly, but with this plugin no.

**Comment by smdol** [comment] 2016-04-11 19:52
The QA team does have an Xperia z3, so we can try to reproduce the error.  Can you say which version of Android it runs, and which apps you experience the reset with?  If you are building the apps, which version of Unity is it, and do you see the issue with the SDK's demo scene?

**Comment by semangu** [comment] 2016-04-11 21:13
My android version is 5.1.1, the apps are all VR app made with Unity. if you want can try my game: https://play.google.com/store/apps/details?id=com.AloneVR.AloneVrGame 
My Unity version is 5.3.4.
And i try the Cardboard SDK 0.7, 0.6, 5.X and 4.X.

if you need i can send a video which the issue.

Thank for you help.

**Comment by smdol** [comment] 2016-04-11 21:14
Oh yes, please send a video.

**Comment by semangu** [comment] 2016-04-11 21:20
https://play.google.com/store/apps/details?id=com.AloneVR.AloneVrGame

**Comment by semangu** [comment] 2016-04-11 21:22
Can you see the AutoRecenter?

**Comment by smdol** [comment] 2016-04-11 21:30
I see it.  So it looks like it continues to reset itself after the headphones are put in?

**Comment by semangu** [comment] 2016-04-11 21:34
Yes the issue continue but it i plug out the headphone it works fine again.

**Comment by smdol** [comment] 2016-04-11 23:26
We've tried running your app on the Sony Xperia z3 (Android 5.1.1), and cannot reproduce the problem when plugging in headphones.  Do you have any other apps or processes running that might steal CPU time because of the headphones?

**Comment by semangu** [comment] 2016-04-11 23:30
i don´t know, but i,m going to restore de mobile to factory settings and formatting the memory, and then talk with you.

thanks again.

**Comment by semangu** [comment] 2016-04-12 00:40
i just restore the device and erase all and the issue continue for me. 

i´dont undestard why in yours z3 works fine and in my z3 not work correctly.

**Comment by le-zim** [comment] 2016-05-01 12:48
Hi all !
I have the same issue with my xperia z3 compact !
hope the Marshmallow update will fix it :)
Note my xperia is stock rom. maybe some application installed disturbed the sensor .... :|

In noticed this on the "alien apartment" app.

**Comment by licaon-kter** [comment] 2016-05-13 20:16
> hope the Marshmallow update will fix it :)

Nope, having it on Z3 6.0.1 too :(

**Comment by licaon-kter** [comment] 2016-05-13 20:34
No joy on Xperia Z3 6.0.1 either.
Tested with both MH-750 (box headphones) and other larger ones.
Tested inside the cardboard (maybe the magnet has something to do with it) and outside, same results.

Have this issue: Sisters, Lanterns, Cardboard Camera, Youtube
Not having this issue: Fibrum Roller Coaster VR.

Should I report this to https://github.com/googlesamples/cardboard-java or somewhere else?

**Comment by DeVereor** [comment] 2016-06-01 03:44
Please tell me someone knows why this happens and how to fix it. Just tried VR headset for first time and so very unhappy every single app resets the gyro if headphones are plugged in to my Z3 :/
Can't find anything useful on Google

**Comment by le-zim** [comment] 2016-07-24 13:11
still have the same bug with the latest stock rom update on my Z3 compact (23.5.A.0 575), for Unity based apps.

**Comment by arnowelzel** [comment] 2016-08-02 20:39
JFTR: Me too :-/

**Comment by countstex** [comment] 2016-09-07 12:56
Just bought my first ever VR headset for use with my Sony Xperia Z2 and have the exact same issue. Interestingly I noticed it only occurs when the app is actually outputting sound. I used the inbuilt tour guide app, and whilst the lady was explaining what I was seeing, the device constantly recentered the view, but the moment she had finished and the sound clip stopped I could look around fine. Very odd!

**Comment by sunnytllw** [comment] 2016-11-04 06:29
I have xperia Z2 running latest firmware Marshmallow and I just bought VR headset and experiencing the same issue. The video auto centre whenever i try to see on sides. Well when the problem occured i was wearing the headphones. I will try to use the VR without headphones and see what happens. Very strange problem, If anyone has solution, please help!!

**Comment by sunnytllw** [comment] 2016-11-04 06:40
I just tried without plugging headphones and I have experienced no problem. The video is not self resetting to centre.

**Comment by hkoli2** [comment] 2016-11-05 13:22
hey guys can you suggest me a headphones which is great for VR, right now I am considering Bose SoundTrue II, which I found on a [site](http://headphoneshelper.com/best-headphones-under-200/). So guys what do I do ?

**Comment by alimoeeny** [comment] 2016-11-05 13:48
IMHO, the only consideration regarding headphones in VR is weight, and bulk, since you already have something heavyish on your head, may I suggest the new JBird https://www.youtube.com/watch?v=77aeW3bsCzc

**Comment by Fryk** [comment] 2016-11-21 17:12
Hi. Still fighting with this issue. I have Xperia Z2 (D6503) with 6.0.1. This happen when I connect big headset with combo but also with original headphones. This happen only in cardboard view. normal 360 works well.

**Comment by pseudocolor** [comment] 2017-01-15 16:59
this headphone - camera reset issue is happened also with my xperia z2 running android 5.1.1
I've tried to disable surround system and any other headphone setting, but the problem persist
please help..

**Comment by arnowelzel** [comment] 2017-01-15 17:19
Now half a year passed without any change - I think, this problem will never be solved :-(

**Comment by licaon-kter** [comment] 2017-01-15 17:40
Did anyone get a chance to test on NDP4 ? I forgot to... :(

**Comment by Witolski** [comment] 2017-01-17 15:41
This is with smart connect,  the app kicks in when you connect headphones and hides a window behind the vr app.  Switch to it and close it and it stops centering.  Not found a way to disable it yet though but it's definitely the cause.

**Comment by arnowelzel** [comment] 2017-01-18 07:33
@Witolski This does not happen here with a Z3 Compact. No window from SmartConnect. I even disabled SmartConnect completeley - no change. The view still automatically jumps to the center as soon as there is a headphone plugged in. This also happens, when the headphone is already plugged in, before I start a VR app.

**Comment by pseudocolor** [comment] 2017-01-18 07:35
I've disable smart connect, and make sure its stopped but the camera reset issue still persist

Sent from Yahoo Mail on Android 
 
  On Tue, Jan 17, 2017 at 22:41, Witolski<notifications@github.com> wrote:   
This is with smart connect, the app kicks in when you connect headphones and hides a window behind the vr app. Switch to it and close it and it stops centering. Not found a way to disable it yet though but it's definitely the cause.

**Comment by Witolski** [comment] 2017-01-18 08:05
Hmmm you're correct,  it seemed to help just once (dismissing the window) but since then it's back,  same when disabled. Sorry for false alarm! 
There's an app that lets you customise what the buttons on the headphones remote do,  and allows you to set them all to 'no action' -  might try that.

**Comment by Fryk** [comment] 2017-04-19 20:41
Well looks like we will never got fix for it.

**Comment by Witolski** [comment] 2017-04-19 20:42
I bought an s5!

**Comment by miraleung** [comment] 2017-04-19 20:42
@anokta Could you please confirm?

**Comment by Fryk** [comment] 2017-04-19 20:54
I've just opened Cardboard app to check this out.
When headphones connected with no audio does not seems to happen. But when I opened presentation with that white fox and there was music playback, when I was turning around screen get re centered few times.

Z2 6.0.1

**Comment by miraleung** [comment] 2017-04-19 20:59
The Cardboard app does not use Unity - could you please file this issue in the gvr-android-sdk repo?

**Closed by miraleung** 2017-04-19 20:59 UTC
