### ISSUE TITLE
Unity Android: in VR mode (both Cardboard and Daydream), volume control doesn't control media volume

### ISSUE THREAD

**Issue by cdytoby** [googlevr/gvr-unity-sdk#705] opened 2017-08-30 14:48 UTC
Unity Android app, when vr mode is enabled and in stereo view, volume control doesn't control media volume.

Volume control does work in non vr mode.

**Comment by nathanmartz** [comment] 2017-08-30 17:27
This is the intended behavior for Daydream but it's a bug in Cardboard. Unity is working on a fix but I don't have a specific ETA right now. What version of Unity are you using?

**Comment by cdytoby** [comment] 2017-08-31 10:01
2017.1.0p3

But how to control audio volume in Daydream?

**Comment by nathanmartz** [comment] 2017-08-31 13:46
In daydream the volume should be controlled by the buttons on the daydream controller.

**Comment by aAAC** [comment] 2017-09-18 09:54
I'm using
Unity2017.2.0b11
GVR Unity v1.70.0

As soon app enters in VR mode it crashes on Samsung Note 8 and stucks on S8, can't load VR veiw

Any help will be much appreciated!

**Comment by vinhui** [comment] 2017-09-18 11:16
@aAAC please create your own issue, and a logcat might be useful

**Comment by aAAC** [comment] 2017-09-18 22:01
Alright, thanks @vinhui  for the suggestion

**Comment by rusmaxham** [comment] 2017-11-08 21:09
The volume buttons should be fixed for Cardboard in Unity 5.6.3f1, 2017.1.1f1, and 2017.2.0f3.

**Closed by rusmaxham** 2017-11-08 21:09 UTC
Labels: Unity bug
