### ISSUE TITLE
how to track the head position in new gvr sdk 1.60

### ISSUE THREAD

**Issue by MartinjMartin** [googlevr/gvr-unity-sdk#638] opened 2017-06-28 08:04 UTC
I was using the gvr sdk 1.30, which had a gvr head script which tracks the head position . Now i am using  gvr sdk 1.60 and can some one please tell which script is performing this head tracking function in gvr sdk 1.60

**Comment by Yerchick** [comment] 2017-07-01 12:00
Same question! How to change position in VR?

**Comment by vinhui** [comment] 2017-07-03 08:24
The head tracking is now baked into the unity engine.

**Comment by MartinjMartin** [comment] 2017-07-03 08:57
Actually i need to create a monoscopic view ..so if  i am giving the sdk as none in inspector, head tracking is not done... so i cant get a 360 view... do we need to write our own script for head tracking (for the monoscopic view)

**Comment by vinhui** [comment] 2017-07-03 09:01
See #532

**Comment by MartinjMartin** [comment] 2017-07-03 12:54
@vinhui  is it possible to switch the sdk in inspector through an editor script from none to cardboard and cardboard to occulus .. i tried many ways but nothing works... your help will be really appreciated

**Comment by vinhui** [comment] 2017-07-03 14:10
These topics have been heavily discussed here see for example #640

**Comment by rusmaxham** [comment] 2017-11-08 21:24
Duplicate of https://github.com/googlevr/gvr-unity-sdk/issues/703.

**Closed by rusmaxham** 2017-11-08 21:24 UTC
