### ISSUE TITLE
Camera horizontally stretched when switching from VR Cardboard to VR None

### ISSUE THREAD

**Issue by peterept** [googlevr/gvr-unity-sdk#640] opened 2017-06-29 02:45 UTC
Hi,

When I exit cardboard mode I use `VRSettings.LoadDeviceByName("None");` wait til next frame and call `VRSettings.enabled = true;`.

When I do this I am back in mono mode, but the screen is stretched horizontally to double (like I am seeing a single eye but double width on the screen).

I'm using Unity 5.6.1p4.

I tried reseting the camera's projectionMatrix, and whilst it does fix the distortion - I can't use this as a fix because then I can't enable the user to zoom via the camera's fieldOfView setting.

Is there another work-around?

**Comment by peterept** [comment] 2017-06-29 04:03
For anyone else, I found a work-around using 2 cameras:

- Add a duplicate Main Camera. On one set it to VR mode "none - main window".
- On second Camera set VR mode to "both" and set its depth to -2 (behind the other camera).

Then any cardboard distortions on the VR camera won't effect the non-vr camera.

**Comment by antoniohof** [comment] 2017-06-29 13:21
I think this is the same as this: #628

**Comment by peterept** [comment] 2017-06-30 10:22
Thanks. I can confirm it is the same problem and that `Camera.main.ResetAspect (); ` does fix it.

BUT, that work-around on IOS leave a frame where the distortion is visible and then it is fixed - which is very ugly and makes the app look buggy.

I ended up using this solution (over the 2 camera approach) because it made my logic for camera management easier. 

However, to avoid the 1 frame of distortion, I use a black overlay to fade out the screen, then switch out of cardboard, then fade it back in thus hiding the frame.

Thanks for your response.

**Comment by fredsa** [comment] 2017-08-05 06:57
You mentioned setting `VRSettings=true` (rather than `false`). Can you try you `SwitchOutOfVr()` coroutine from https://github.com/googlevr/gvr-unity-sdk/wiki/Switching-between-VR-and-non-VR-at-runtime and confirm whether you still see the incorrect aspect ratio during switching?

Note that there are effectively two ways to leave VR:
1. Call `VRSettings=false` (but leave the Cardboard VR SDK active so you can later set it back to `true`)
2. Call `VRSettings.LoadDeviceByName("")` (meaning the **None** device), which will automatically also set `VRSettings=false`.

**Comment by fredsa** [comment] 2017-08-05 07:11
You can vote on the Unity issue which is causing you to have to call `ResetAspect()` here:
https://issuetracker.unity3d.com/issues/android-vrcardboard-aspect-ratio-not-preserved-when-switching-from-vr-cardboard-to-non-vr-vrsettings-dot-enabled-equals-false

**Comment by fredsa** [comment] 2018-01-05 19:36
Duplicate of #628 

This is fixed in:

Unity 5.6.4p2 and later
Unity 2017.1.2p3 and later
Unity 2017.2.0p2 and later

This means that you should no longer have call ResetAspect() after switching out of VR.

**Closed** 2018-01-05 23:57 UTC
Labels: duplicate, Unity bug
