### ISSUE TITLE
Double Vision Samsung S7 — distortion wrong when resolution is not WQHD

### ISSUE THREAD

**Issue by justinwasilenko** [googlevr/gvr-unity-sdk#421] opened 2016-12-26 20:22 UTC
I just updated Minos Spacefighter to use the new GVR 13 Unity build. This has caused a tonne of issues for everyone using a Samsung S7 and has caused a serious drop in the ratings of the game.
Last time I updated the game using Unity 5.4.3 and the GVR 0.85 which also have issues with the Samsung S7.

So I'm stuck again with bad reviews on my app due to problems with the GVR plugin.

I have instructed people to rescan their QR codes and delete the local cache and data of both the Cardboard app and the Minos Spacefighter app but that hasn't solved the issues.

Is this a known issue? I also had one report with the Asus Zenphone 2 of having the same problem.

**Comment by justinwasilenko** [comment] 2016-12-26 20:26
Sorry the issue with the Asus Zenphone 2 is the gyroscope doesn't work.

**Comment by nathanmartz** [comment] 2017-01-03 04:01
Sorry for the issues. We'll take a look with our friends at Unity.

**Comment by nathanmartz** [comment] 2017-01-03 04:01
Can you post a play store link to your game?

**Comment by justinwasilenko** [comment] 2017-01-03 07:01
Here you go: https://play.google.com/store/apps/details?id=com.endspacevr

**Comment by MrDelegateCB** [comment] 2017-01-04 08:46
Hey, I'm also having the same issue. I think it has something to do with dpi of the device. Because in the review, reported dpi was 640 while in actual device has dpi of 577.

**Comment by MephestoKhaan** [comment] 2017-01-08 13:30
Same problem here with S7s. Sometimes it is more extreme when disabling distortion and doing it in the vertex-shader.

**Comment by Saraceni** [comment] 2017-01-21 20:42
I am having this exact same problem with my Galaxy S7 Flat. I am using Unity 5.5.of3 Personal and Google VR SDK 1.0. It works fine in the majority of devices, but in the Galaxy S7 the offset between left and right eyes are too big, making it impossible to have an immersion using any headset.

**Comment by Saraceni** [comment] 2017-01-21 20:47
![double-vision-gvr](https://cloud.githubusercontent.com/assets/3177383/22177684/000e9db8-e00a-11e6-8186-d52c0b0f389d.png)

**Comment by miraleung** [comment] 2017-01-22 08:09
Thanks for the report, we'll look into this.

**Comment by kasradzenika** [comment] 2017-01-24 20:50
I'm having the same issue

![screenshot](https://s29.postimg.org/unohye0xz/16326952_10208277741087817_1705150330_o.png)

**Comment by tomihr** [comment] 2017-03-03 12:12
I also have double vision problem on Samsung Galaxy S7 flat.

**Comment by gaffkins** [comment] 2017-03-06 22:19
The same problem :(

**Comment by TANGSTEN** [comment] 2017-03-11 06:35
I got split eye vision after Android 7.0 came out for my Samsung S7. Worked great on Android 6.0. The screen is looking to far to each side on each eye on almost every previous build of Unity up till 5.5f2. The 5.6 beta has very poor results. Google VR version is 1.3. My Android SDK supports up to target build 24.
Please fix this soon.
![screenshot_20170310-222258](https://cloud.githubusercontent.com/assets/6656249/23821247/45fea816-05e1-11e7-894b-279aa1f9c105.png)

**Comment by ninjingames** [comment] 2017-03-11 10:35
Samsung apparently reduced the screen resolution of the Galaxy S7 from its native 2560x1440 to 1920x1080 with the update to Android 7. [This article](http://www.androidcentral.com/galaxy-s7-nougat-defaults-1080p-look-samsungs-new-display-scaling-options) is about a beta build, but I believe it's in the final as well.

Could we please get an update on the situation from somebody at Google? The SGS7 is probably one of the most popular phones for VR applications and if it doesn't work correctly with the GVR SDK it's really tough for us developers dealing with all the bad ratings and complaints from users.

**Comment by Saraceni** [comment] 2017-03-11 20:13
I'm having this problem in a S7 running 6.0.1 Marshmallow. I think the resolution is not the problem.

**Comment by kasradzenika** [comment] 2017-03-11 20:22
@Saraceni resolution is the cause of the problem. This is, I think, how unity creates VR frames (black borders):
1. unity first creates bottom and middle frames to fit the virtual resolution (which is bigger than then the actual), so the frames appear zoomed in on the device towards the bottom-center of the screen
2. then it creates frames on the top and at the left and right edges of the screen which get created properly - using the actual resolution

again, this is just a guess based on the screenshots

**Comment by TANGSTEN** [comment] 2017-03-11 21:43
![screenshot_20170311-132825](https://cloud.githubusercontent.com/assets/6656249/23827098/9f76a72a-0660-11e7-80f9-eed0ef1aafa9.png)

**Comment by TANGSTEN** [comment] 2017-03-11 21:46
Just as I thought. I rooted my Samsung S7 and downgraded back to Marshmallow 6 0.1 and kept Google VR current to 1.3 and Unity3D 5.5.2f1 and the Google VR worked just as it always had. The problem is Android 7.0. Please fix this guys. It's the android build and I lost my apps to figure it out . The sacrifices I make because of you Unity3D or Google.

**Comment by tomihr** [comment] 2017-03-12 07:56
Yes now when you take screenshot it is 1920xx1080, why Samsung did that?

**Comment by TANGSTEN** [comment] 2017-03-12 09:56
This the VR game in action on Samsung Galaxy S7 for GoogleVR. Marshmallow 6.0

https://youtu.be/AsO8nVP2Auc

http://www.joesid.com

**Comment by tomihr** [comment] 2017-03-12 10:02
Guys solution is to change screen resolution in display settings. Just done this on my Samsung S7 and it works, you need to change it to wqhd.

**Comment by TANGSTEN** [comment] 2017-03-12 10:04
@tomihr Thank you for the heads up. This is why I posted here. :)

**Comment by baroquedub** [comment] 2017-03-21 15:59
Thanks @tomihr 

Now to explain this to our users :) ...

(couple of useful screenshots here [http://gadgetguideonline.com/s7/how-to-change-screen-resolution-of-galaxy-s7-and-s7-after-android-nougat-update/](Scroll down to "How to change screen resolution of Galaxy S7 and S7 after Android Nougat update?"))

**Comment by ninjingames** [comment] 2017-03-24 10:16
This is really a problem that Google has to fix. We can't force all SGS7 users to go into their settings and change the resolution.

It's a problem that Google is capable to fix, since the official Google Cardboard app works correctly with the lower resolution, so Google has a code branch somewhere that works correctly. Also the SGS7 properly reports the changed dpi for the different screen resolutions you can select, so the GVR SDK should be able to work with whatever resolution the user has selected.

@miraleung You wrote "we'll look into this" two months ago. Any update on the situation?

**Comment by dbuck** [comment] 2017-03-29 19:39
We're also seeing the problem here, and would appreciate a fix that doesn't require the end-user to change the system resolution

**Comment by miraleung** [comment] 2017-03-29 20:04
We haven't been able to repro for recent releases - could you please try upgrading to v1.3 of the GVR Unity SDK, and Unity 5.6.0f2?

**Comment by Zoriak22** [comment] 2017-04-02 11:01
The resolution and Android 7.0 is NOT the problem. This issue with S7 devices was posted in 2016 august too with 6.0, same double vision issue. The problem is somehow in the SDK.

**Comment by ninjingames** [comment] 2017-04-02 16:08
@miraleung The problem still exists for GVR1.3 and Unity 5.6.0f3.

Steps I took to reproduce the problem:
- Create new project in Unity 5.6.0f3
- Import Google VR SDK v1.3.0
- Open GVRDemo.scene
- Set Build target to Android, turn on "Virtual Reality Supported" in player settings, add Cardboard to "Virtual Reality SDKs", Change Minimum API Level to Android 4.4
- Build and deploy to Galaxy S7 with FullHD Resolution
- Run DemoGVR => Double vision
- Change resolution to WQHD and run again => app displays correctly
- Switch resolution back to FullHD => fail again

Are you sure that the Galaxy S7 you've tried to reproduce the problem with is set to FullHD resolution instead of the displays native WQHD?
If you set the screen resolution to WQHD the 3D effect works correctly, but unfortunately all Galaxy S7 were changed to use FullHD by default during the upgrade to Android 7.0, so it affects the majority of all Galaxy S7 owners who didn't manually change resolution back to WQHD.

@Zoriak22 I think this issue (which was posted 26 Dec 2016, not August 2016) really is about resolution and Android 7.0, because everything works correctly with the resolution set to WQHD (which was the default and only setting on Android 6.0 and was changed to FullHD during the update to Android 7.0).

**Comment by Zoriak22** [comment] 2017-04-02 16:36
[https://github.com/googlevr/gvr-unity-sdk/issues/271](url)

Not August, July, sorry. It's a really old issue, and not connected with resolution, because the issue was already happened on 6.0 version too. Maybe changing resolution on your S7 variant can help, but on mine still no change. It's  SM-G930F modell.

I try to reproduce also the problem and give you a feedback.

**Comment by guneyozsan** [comment] 2017-04-02 17:21
I also confirm the view is out of focus in S7 set to Full HD both in Android 6 and 7 (you see double), but it is normal in WQHD. This is the case for all versions of Unity from 5.6.0b9 to 5.6.0f3 and Google VR SDK 1.20 and 1.30.

I was thinking Google VR SDK was incompatible with Gear VR (in cardboard mode not oculus) and had ordered a different viewer. Thanks to this topic setting to WQHD resolved the issue. Honestly I didn't even know my S7 was downsized until I find this topic. I don't think any regular user can notice and change the setting for an app/game that behaves buggy.

**Comment by miraleung** [comment] 2017-04-02 18:09
Could you please see if you can reproduce the issue with the NDK TreasureHunt sample (https://github.com/googlevr/gvr-android-sdk/tree/master/samples/ndk-treasurehunt)? This will help us identify where the root cause is located.

**Comment by jdduke** [comment] 2017-04-05 18:26
Another thing to try is installing the latest version of [Google VR Services](https://play.google.com/store/apps/details?id=com.google.vr.vrcore&hl=en). The GVR SDK used a set of DPI overrides for certain devices which misreport their DPI. However, such DPI overrides only work properly when the device is configured for *native* resolution. The latest version of Google VR Services might have a fix for this issue.

**Comment by baroquedub** [comment] 2017-04-19 21:15
Closed as in fixed? Last build I did on Unity 5.5.1 / GVR10.3, it was still a problem.

Can you confirm whether you're closing because it's fixed in Unity 5.6's built-in GoogleVR support?

**Comment by Zoriak22** [comment] 2017-04-19 21:28
The problem still exists.

**Comment by miraleung** [comment] 2017-04-19 21:31
Following @jdduke's fix should solve the issue.

**Comment by helge79** [comment] 2017-04-21 11:01
We are also experiencing this issue after upgrading our Galaxy S7 to Android 7. Our configuration: Unity 5.5.2f1, GVR SDK 1.30 and latest Google VR services.

Screenshot of GVRDemo with default setting (FullHD):

![screenshot_20170421-125608](https://cloud.githubusercontent.com/assets/11921029/25274837/686ff504-2692-11e7-8008-49ed488124e3.png)

Screenshot of GVRDemo with resolution changed to WQHD:

![screenshot_20170421-125738](https://cloud.githubusercontent.com/assets/11921029/25274840/6c7176dc-2692-11e7-90f8-e79d82f9c695.png)

**Comment by helge79** [comment] 2017-04-21 12:02
@miraleung The NDK TreasureHunt sample works fine. I just cloned the repository and built the APK -
 find the screenshots below. Anything else we can assist you with in finding the root cause of this issue?

Screenshot of TreasureHunt (FullHD):

![screenshot_20170421-135648](https://cloud.githubusercontent.com/assets/11921029/25276498/d2a2112a-269a-11e7-824c-59a6f472c424.png)

Screenshot of TreasureHunt (WQHD):

![screenshot_20170421-135547](https://cloud.githubusercontent.com/assets/11921029/25276503/d5dccfba-269a-11e7-8026-1048357961e0.png)

**Comment by andyz** [comment] 2017-05-04 09:37
Get exactly same as helge79 with Unity 5.5.1 and GVR 1.4. Changing s7 phone res fixes, but this is not a solution (you can not ask public using your app to chnage their resolution). Have latest Google VR Services

**Comment by miraleung** [comment] 2017-05-15 20:13
Could you please try this with Unity 5.6 and Cardboard enabled in Player Settings?

**Comment by Chris-1993** [comment] 2017-05-18 21:21
I tested it with Unity 5.6.1f1 (Cardboard enabled in Player Settings) and GoogleVR SDK 1.50.0 on a Galaxy S7 (SM-G930F) with Android 7.0.

Random Package Name & GoogleVR Services app installed: **Doesn’t work**
Random Package Name & WITHOUT GoogleVR Services app installed: **WORKS**
Package Name of a published Cardboard App & GoogleVR Services app installed: **Doesn’t work**
Package Name of a published Cardboard App & WITHOUT GoogleVR Services app installed: **Doesn’t work.**

Between all tests I killed all tasks on the phone and possibly rebooted the phone. Otherwise you won't be able to see the changes. Furthermore the phone had an internet connection.

All in all it’s the same result as in other Unity and GoogleVR SDK (except < 0.7.2) versions.



The results with GoogleVR/Cardboard SDK < 0.7.2 look like this:
 
Random Package Name & GoogleVR Services app installed: **Doesn’t work**
Random Package Name & WITHOUT GoogleVR Services app installed: **WORKS**
Package Name of a published Cardboard App & GoogleVR Services app installed: **Doesn’t work**
Package Name of a published Cardboard App & WITHOUT GoogleVR Services app installed: **WORKS.**



Please also check out this falsely closed issues. There are more information related to this problem.
https://github.com/googlevr/gvr-unity-sdk/issues/271 (here you also find a explanation why I used different Package Names)
https://github.com/googlevr/gvr-unity-sdk/issues/315


Sorry for my Englisch. I’m not a native Englisch speaker.

**Comment by mcfn** [comment] 2017-06-07 05:58
We have same problem for S7 in Android 7.0, any update for this issue?

**Comment by Zagrava** [comment] 2017-07-24 09:41
Same problem with S7, no solution so far?

**Comment by Zagrava** [comment] 2017-07-26 09:50
P.S. Installing project in offline mode runs the game perfectly, but if you install it being online - this bug appears.
Something is synced with the google store?

**Comment by fredsa** [comment] 2017-08-31 16:20
Likely same issue as described in https://github.com/googlevr/webvr-polyfill/issues/273

**Comment by jdduke** [comment] 2017-09-07 19:37
Just wanted to share an update. We've tested a tentative fix against several apps, and the results are promising. The fix would go out as part of a Google VR Services update at the end of the month. We'll post more when the rollout starts to get confirmation of the fix. Thanks for your patience.

**Comment by AlexanderStohr** [comment] 2017-09-10 19:01
Samsung Galaxy S7 (SM-G930F): able to confirm the problems with too wide eye-views (clipped on the short edges) on many applications from Google Play Store. Android system version is 7.0.

now eagerly hoping for the possible global fix from jdduke right above!

**Comment by parkitny** [comment] 2017-09-24 06:25
Any further progress on a proper bug fix for this issue?

**Comment by rpassareti** [comment] 2017-09-26 18:36
even changing the resolution on my s7, the displays still be in the wrong position
seems like the circle is bigger

**Comment by fredsa** [comment] 2017-09-28 15:48
The Google VR services update @jdduke [mentioned](https://github.com/googlevr/gvr-unity-sdk/issues/421#issuecomment-327902050) above, initially scheduled to go out this week, has been pushed to next week. Expect the staged rollout of the VrCore update to begin on Monday, October 2, 2017.

To see the current version of VrCore on your device, use:
**Settings > Apps > ︙ > Show system apps > Google VR Services**

**Comment by jonny2027** [comment] 2017-10-03 11:14
@fredsa Can you tell us what version of VRCore will have the fix in for this issue?

**Comment by jdduke** [comment] 2017-10-03 16:37
The Google VR Services with the tentative fix should have the following version name: 1.10.170249286. Rollout will hit 25% today, and 100% be the end of the week.

**Comment by guneyozsan** [comment] 2017-10-06 18:57
I can confirm this is fixed for me after receiving the Google VR Services version 1.10.170928015.

**Closed** 2017-10-06 23:36 UTC
Labels: bug

**Comment by helge79** [comment] 2017-10-13 08:46
I cannot confirm this is fixed for me. Our apps built with Unity 5.5.2f1 and GVR SDK 1.30 still do not work in Full HD mode after updating Google VR services to 1.10.170928015. Should this work or is Unity 5.5 and GVR SDK 1.30 the show-stopper here?

**Comment by guneyozsan** [comment] 2017-10-13 09:59
If it helps our versions are Unity 2017.1.1p2 and GVR 1.60.

**Comment by fredsa** [comment] 2017-10-16 18:24
@helge79 Native integration of Google VR into Unity exists from Unity 5.6 onward, so at the moment that's Unity 5.6 and 2017.

Unity 5.5 does not have native Google VR integration, so will not be affected by the installed Google VR Services.

**Comment by AlexanderStohr** [comment] 2017-10-16 21:35
i feel like i got all of the latest updates - but for the S7 i see it only fixed for the low and medium resolution mode. it still does not work for the high resolution "W" mode. sorry to say.

**Comment by jules43** [comment] 2017-10-19 07:42
I am working with Unity 5.3.8p2 and Google VR Unity plugin version 1.40 and an older build, and have been seeing this problem.

I can confirm that the problem occurs in FHD mode and is fixed in WQHD mode on my Samsung S7 (Android 7.0 Aug patch).

The problem still occurs when installing the 1.10.170928015 version of Google VR Services.

**Comment by helge79** [comment] 2017-10-19 07:56
@fredsa Thanks for clarification, Fred. If updating Unity would not be an option can you think of any possible workaround we might apply?

**Comment by fredsa** [comment] 2017-10-19 16:19
@jules43 The current Google VR SDK requires Unity 5.6 or later.
(Unity 5.3 does not include native integration of Google VR, which means the SDK is handling a lot more of the rendering implementation. For the update to Google VR Services to help, please update to Unity 5.6 and the latest Google VR SDK.)

**Comment by jules43** [comment] 2017-10-19 16:42
@fredsa Thanks for the clarification
