### ISSUE TITLE
"X" back button in cardboard overlay on android is closing the app

### ISSUE THREAD

**Issue by jgnoel86** [googlevr/gvr-unity-sdk#601] opened 2017-06-02 19:20 UTC
Having issues in our own app with the X button I've setup a simple scene with nothing else in the project.  I understand on daydream it should close the app. But my understanding was on Cardboard it would act like iOS and trigger Input.GetKeyDown(KeyCode.Escape)

[CardboardXTest.unitypackage.zip](https://github.com/googlevr/gvr-unity-sdk/files/1048702/CardboardXTest.unitypackage.zip)

**Comment by nathanmartz** [comment] 2017-06-03 00:35
Are you using Unity 5.6? If so, this was a regression and should be fixed in an upcoming bugfix release.

**Comment by aschau** [comment] 2017-06-09 00:44
I just tested it with several builds on Unity 5.6.1p2 which was recently released and the issue is fixed.

**Comment by cdytoby** [comment] 2017-06-14 13:18
I can confirm that 5.6.1p3 fixed this issue. But it's unity patch release. Hope this will be in unity 5.6.2 or 2017.1 release.

**Comment by fredsa** [comment] 2017-08-06 19:54
Closing, after verifying that close/back button are both (still) working as expected in Unity 5.6.2p3.

* When clicking ✕ (close) or ◀ (back), your Unity app will get an escape key press
* In development and testing you can inject an artificial escape press using

```shell
 adb shell input keyevent KEYCODE_ESCAPE
```

* To handle this in your code, look for the key down event:

```C#
void Update() {
  if (Input.GetKeyDown(KeyCode.Escape)) {
    // Android close icon or back button tapped.
    Application.Quit();
  }
}
```

**Closed by fredsa** 2017-08-06 19:54 UTC
Labels: Unity bug

**Comment by slowizzm** [comment] 2018-05-05 20:37
I am on 2017.4.2f2 LTS and this is still an issue on android. I have updated the code to return user to the main menu via SceneManager. This works on iOS but is closing the app on android. 

```void Update() {
      if (Input.GetKeyDown(KeyCode.Escape)) {
        SceneManager.LoadScene("MainMenu");
      }
```

**Comment by ddrocco** [comment] 2018-05-10 19:52
Thanks for reporting, we'll look into it!

**Comment by slowizzm** [comment] 2018-05-10 22:00
this issue seems to be resolved now, functioning as expected.

**Comment by kkarannn** [comment] 2018-07-12 10:47
I am still facing this issue in 2017.3.1f1. The X button in daydream crashes/closes the app.
get keycode escape is not working. I want to change the scene and return to 2D mode in the app.
What is the fix for this??
