### ISSUE TITLE
Click in Game view as Cardboard touch Input

### ISSUE THREAD

**Issue by xavis** [googlevr/gvr-unity-sdk#994] opened 2018-12-26 14:50 UTC
Summary:
It's important to be able to simulate at least a touch on Unity's Play mode when using Cardboard SDK, as if not input is completely impossible to simulate via the SDK itself.

I don't know if this was active before and was deprecated, but anyway detecting click on Game view or adding a functionality as a loader is important to add some comfortable behaviour to Cardboard compatible devices.

Found using:
 * Google VR SDK version: 1.180.0
 * Unity version: 2018.2.6f1
 * Phone manufacturer, model, and O/S version: Unity Player
 * Viewer manufacturer & model: Unity

Steps to reproduce the issue:
 1. Add GoogleVR Unitypackage.
 2. Open HelloVR.
 3. Switch build platform to Android
 4. Enable VR support and add Cardboard as SDK
 5. Play
 6. Try clicking on screen or Treasure object's from playrer, nothing happens.

Workarounds:
Maybe add a behaviour to click on screen when Cardboard is the first SDK selected, or add a functionality like a loader based on keep focusing an object a specific amount of time.

Additional comments:
Sorry if this was discussed before, I didn't find this specific case.

**Comment by rusmaxham** [comment] 2019-01-02 23:57
This is a duplicate of [issue 985](https://github.com/googlevr/gvr-unity-sdk/issues/985).

**Closed by rusmaxham** 2019-01-02 23:57 UTC
Labels: duplicate
