### ISSUE TITLE
Toggle VR mode at runtime in Unity2017.1.0p5

### ISSUE THREAD

**Issue by blacky427** [googlevr/gvr-unity-sdk#770] opened 2017-11-03 03:10 UTC
<Brief summary of the issue you encountered>

Found using:
 * Google VR SDK version: Unity build-in
 * Unity version: 2017.1.0p5
 * Phone manufacturer, model, and O/S version: iPhone SE, iOS 11.0

Steps to reproduce the issue:
1. Follow the instruction from [https://github.com/googlevr/gvr-unity-sdk/wiki/Switching-between-VR-and-non-VR-at-runtime](https://github.com/googlevr/gvr-unity-sdk/wiki/Switching-between-VR-and-non-VR-at-runtime)

2. When you switch to VR mode at portrait, you will get weird effect in VR mode.
![img_0276](https://user-images.githubusercontent.com/12066593/32359216-58bac9aa-c01a-11e7-94f4-0266720d80a4.PNG)

Workarounds:
1. Trigger SwitchToVR only when device orientation is landscape left. Even so, still have chance
to get the weird effect if you switch your device's orientation quickly.
![img_0275](https://user-images.githubusercontent.com/12066593/32359234-78cc688e-c01a-11e7-81d1-ceca190b7449.PNG)

```
private IEnumerator SwitchToVR()
{
    yield return new WaitUntil(() => Input.deviceOrientation == DeviceOrientation.LandscapeLeft);

    VRSettings.LoadDeviceByName("daydream"); // Or "cardboard" (both lowercase).
    
    // Wait one frame!
    yield return null;
    
    // Now it's ok to enable VR mode.
    VRSettings.enabled = true;
}
```

**Comment by tedruxpin** [comment] 2017-11-03 17:44
Thank you for reporting this issue, and for the work-around.  I have created a bug in our tracker and will ask one of our devs to respond if there is another alternative.

**Comment by tedruxpin** [comment] 2017-11-03 20:56
Hello, it turns out this is a duplicate of issue [#602](https://github.com/googlevr/gvr-unity-sdk/issues/602).  An alternative workaround can be found [here](https://github.com/googlevr/gvr-unity-sdk/issues/602#issuecomment-339157524).  I will close this issue for now, please reopen if this does not resolve your issue.

**Closed** 2017-11-03 21:13 UTC

**Comment by fredsa** [comment] 2018-01-17 18:53
Will continue tracking this issue as #838.
