### ISSUE TITLE
App crashing on Launch on Samsung Galaxy phones

### ISSUE THREAD

**Issue by saeidfarivar** [googlevr/gvr-unity-sdk#771] opened 2017-11-03 17:14 UTC
Cardboard app won't run on Samsung Galaxy phones.

Found using:
 * Google VR SDK version: All SDK versions
 * Unity version: All Unity versions
 * Phone manufacturer, model, and O/S version: Galaxy S8, Galaxy Note8, running Android 7.1.2
 * Viewer manufacturer & model: Google Cardboard Default

Steps to reproduce the issue:
 1. Create a sample scene using Unity Version 5.6.0 or later. 
 2. Import GVR SDK 1.100.1. 
 3. Enable Virtual Reality support and only add "Cardboard".
 4. Before Launching app, go to Google's Daydream app and set the view to Cardboard
 5. Launch the sample app, the app will crash...

If SDK version 1.40 or before is used using Unity before 5.6.0, the app will only launch once when the viewer is set to Daydream in Google's Daydream app...

Workarounds:
No workarounds so far... we're receiving a lot of comments that our Cardboard app is not working on Galaxy S8 and Galaxy Note8 phones.

Additional comments:
This doesn't happen on Pixel phones.

**Comment by fredsa** [comment] 2017-11-03 20:23
I believe this is a duplicate of #671

**Comment by fredsa** [comment] 2017-11-03 20:24
If you find that this is a different issues than that one, please let us know.

**Closed by fredsa** 2017-11-03 20:23 UTC
Labels: bug

**Comment by saeidfarivar** [comment] 2017-11-03 21:10
yeah,  

> Settings > Display > Screen resolution > WQHD+ > APPLY

fixes the issue... but keep in mind that I am not switching between VR SDKs, or even enabling/disabling VR...

Any idea when this will be fixed?

**Comment by rusmaxham** [comment] 2017-11-03 22:25
This should be fixed in Unity 5.6.4p1, 2017.1.2p1, and 2017.2.0f3.  This fix also requires VR Services 1.101.0.

**Comment by chelder86** [comment] 2017-12-11 09:19
With VR Services you mean the user must have installed the following app? https://play.google.com/store/apps/details?id=com.google.vr.vrcore&rdid=com.google.vr.vrcore

**Comment by rusmaxham** [comment] 2017-12-12 04:40
Yes, either by having the latest VR Services (vrcore) or GVR SDK for Unity v1.110 or later.

**Comment by chelder86** [comment] 2017-12-12 08:43
So if the app has been built with GVR SDK for Unity v1.10 or later, the installation of the VR Services (vrcore) is NOT needed?

With GVR SDK for Unity v.1.10 or later you mean the version launched after February 2017, right? https://github.com/googlevr/gvr-unity-sdk/releases/tag/schelldemo1.10.0

**Comment by rusmaxham** [comment] 2017-12-12 16:26
If the app has been built with [v1.110](https://github.com/googlevr/gvr-unity-sdk/releases) or later then yes, it does not matter which version of VR Services has been installed.
